"""designer/ide/backend_scaffold.py (FROZEN gate for W5).

The generated backend.py is run as a real process and spoken to over UDP,
as the panel would (docs/CONTRACT.md section 2)."""
import json
import os
import py_compile
import shutil
import signal
import socket
import subprocess
import sys
import tempfile
import time
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.append(str(Path(__file__).resolve().parent))  # after the repo: tests/ui must not shadow ui

from designer.ide.backend_scaffold import (  # noqa: E402
    BACKEND_DIR, FILES, project_slug, render_backend_py, render_readme, render_tags_header, render_tags_json,
    tag_ident, write_scaffold,
)
from designer.ide.design_index import DesignIndex  # noqa: E402
from designer.model.project import DesignerProject  # noqa: E402
from ide_v2_fixture import DECLARED_TAGS, make_project  # noqa: E402


def free_port():
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.bind(("127.0.0.1", 0))
    port = s.getsockname()[1]
    s.close()
    return port


class RenderTests(unittest.TestCase):
    def setUp(self):
        self.index = DesignIndex.build(make_project(), declared_tags=DECLARED_TAGS)

    def test_ident_and_slug(self):
        self.assertEqual(tag_ident("ai.rpm"), "ai_rpm")
        self.assertEqual(tag_ident("mb.pump-1.sp"), "mb_pump_1_sp")
        self.assertEqual(tag_ident("9x.y"), "t_9x_y")
        self.assertEqual(project_slug(self.index), "fixture")
        project = make_project()
        project.name = "  Cockpit Demo #2 "
        self.assertEqual(project_slug(DesignIndex.build(project)), "cockpit-demo-2")
        self.assertEqual(project_slug(DesignIndex.build(DesignerProject())), "hmi")

    def test_tags_json(self):
        text = render_tags_json(self.index)
        self.assertTrue(text.endswith("\n"))
        data = json.loads(text)
        self.assertEqual(data["project"], "Fixture")
        tags = {t["tag"]: t for t in data["tags"]}
        self.assertEqual([t["tag"] for t in data["tags"]], [t.tag for t in self.index.tags()])
        self.assertEqual(tags["ai.rpm"], {"tag": "ai.rpm", "access": "R", "writable": False, "declared": True,
                                          "readers": ["rpm", "rpm2"], "writers": []})
        self.assertEqual(tags["do.pump"]["readers"], ["pump"])
        self.assertEqual(tags["do.pump"]["writers"], ["pump"])

    def test_header(self):
        text = render_tags_header(self.index)
        lines = text.splitlines()
        self.assertTrue(lines[0].startswith("/* Generated by EmbeddedDisplay Studio from Fixture"))
        self.assertIn("#ifndef FIXTURE_TAGS_H", lines)
        self.assertIn('#define TAG_AI_RPM "ai.rpm"', lines)
        self.assertIn('#define TAG_DO_PUMP "do.pump"', lines)
        self.assertIn("#define TAG_COUNT 6", lines)
        self.assertEqual(lines[-1], "#endif")
        self.assertTrue(text.endswith("\n"))

    def test_readme(self):
        text = render_readme(self.index)
        for needle in ("--listen", "--sink", "--period", "--frames", "--daemon-port 5010", "ai.rpm", "do.pump"):
            self.assertIn(needle, text)

    def test_backend_compiles_and_is_stdlib_only(self):
        text = render_backend_py(self.index)
        d = tempfile.mkdtemp()
        self.addCleanup(shutil.rmtree, d, True)
        path = os.path.join(d, "backend.py")
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)
        py_compile.compile(path, doraise=True)
        for name in ("def read_ai_rpm(", "def read_do_pump(", "def write_do_pump(", "def write_do_horn("):
            self.assertIn(name, text)
        self.assertNotIn("def write_ai_rpm(", text)
        self.assertIn('if __name__ == "__main__":', text)
        imports = [line.split()[1].split(".")[0] for line in text.splitlines()
                   if line.startswith(("import ", "from "))]
        allowed = set(sys.stdlib_module_names) | {"__future__"}
        self.assertTrue(set(imports) <= allowed, set(imports) - allowed)


class WriteScaffoldTests(unittest.TestCase):
    def setUp(self):
        self.root = tempfile.mkdtemp(prefix="scaffold-")
        self.addCleanup(shutil.rmtree, self.root, True)
        self.index = DesignIndex.build(make_project(), declared_tags=DECLARED_TAGS)

    def test_writes_and_skips(self):
        result = write_scaffold(self.root, self.index)
        want = [os.path.join(self.root, BACKEND_DIR, f) for f in FILES]
        self.assertEqual(result, {"written": want, "skipped": []})
        for p in want:
            with open(p, "rb") as f:
                self.assertNotIn(b"\r\n", f.read())
        with open(want[0], "w", encoding="utf-8") as f:
            f.write("# mine\n")
        again = write_scaffold(self.root, self.index)
        self.assertEqual(again, {"written": [], "skipped": want})
        with open(want[0], encoding="utf-8") as f:
            self.assertEqual(f.read(), "# mine\n")
        forced = write_scaffold(self.root, self.index, overwrite=True)
        self.assertEqual(forced["written"], want)
        self.assertEqual(sorted(os.listdir(os.path.join(self.root, BACKEND_DIR))), sorted(FILES), "no temp files left")

    def test_bad_root(self):
        with self.assertRaises(ValueError):
            write_scaffold(os.path.join(self.root, "missing"), self.index)

    def test_empty_design(self):
        result = write_scaffold(self.root, DesignIndex.build(DesignerProject()))
        self.assertEqual(len(result["written"]), 4)


class BackendProcessTests(unittest.TestCase):
    """Runs the generated backend and talks CONTRACT 2 to it."""

    def setUp(self):
        self.root = tempfile.mkdtemp(prefix="backend-")
        self.addCleanup(shutil.rmtree, self.root, True)
        write_scaffold(self.root, DesignIndex.build(make_project(), declared_tags=DECLARED_TAGS))
        self.script = os.path.join(self.root, BACKEND_DIR, "backend.py")
        self.cmd_port = free_port()
        self.sink = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.sink.bind(("127.0.0.1", 0))
        self.sink.settimeout(3)
        self.addCleanup(self.sink.close)
        self.client = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.client.bind(("127.0.0.1", 0))
        self.client.settimeout(3)
        self.addCleanup(self.client.close)

    def start(self, *extra):
        proc = subprocess.Popen(
            [sys.executable, self.script, "--listen", f"127.0.0.1:{self.cmd_port}",
             "--sink", f"127.0.0.1:{self.sink.getsockname()[1]}", "--period", "0.05", *extra],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        self.addCleanup(lambda: proc.poll() is None and proc.kill())
        self.frame()  # up and publishing
        return proc

    def frame(self, sock=None):
        data, _ = (sock or self.sink).recvfrom(65536)
        return json.loads(data)

    def command(self, obj):
        raw = obj if isinstance(obj, bytes) else json.dumps(obj).encode()
        self.client.sendto(raw, ("127.0.0.1", self.cmd_port))
        while True:
            data, _ = self.client.recvfrom(65536)
            msg = json.loads(data)
            if msg.get("t") == "ack":
                return msg

    def latest_frame(self):
        # Drain what queued up, then take a fresh one.
        self.sink.setblocking(False)
        try:
            while True:
                self.sink.recvfrom(65536)
        except BlockingIOError:
            pass
        self.sink.settimeout(3)
        return self.frame()

    def test_frames(self):
        self.start()
        f1, f2 = self.frame(), self.frame()
        self.assertEqual(f1["t"], "tags")
        self.assertEqual(f1["src"], "fixture-backend")
        self.assertEqual(f2["seq"], f1["seq"] + 1)
        self.assertIsInstance(f1["ts"], float)
        self.assertEqual(sorted(f1["tags"]), ["ai.fuel", "ai.oiltemp", "ai.rpm", "di.estop", "do.horn", "do.pump"])
        self.assertIs(f1["tags"]["do.pump"], False)
        self.assertEqual(f1["tags"]["ai.rpm"], 0.0)

    def test_commands(self):
        self.start()
        self.assertEqual(self.command({"id": "c1", "cmd": "set", "tag": "do.pump", "value": True}),
                         {"t": "ack", "id": "c1", "ok": True})
        self.assertIs(self.latest_frame()["tags"]["do.pump"], True)
        self.assertEqual(self.command({"id": "c2", "cmd": "set", "tag": "ai.rpm", "value": 1})["err"], "not_writable")
        self.assertEqual(self.command({"id": "c3", "cmd": "set", "tag": "zz.q", "value": 1})["err"], "unknown_tag")
        self.assertEqual(self.command({"id": "c4", "cmd": "set", "tag": "do.pump", "value": "x"})["err"],
                         "bad_value")
        self.assertEqual(self.command({"id": "c5", "cmd": "bogus"})["err"], "unknown_cmd")
        self.assertEqual(self.command(b"{nope")["err"], "bad_json")
        self.assertEqual(self.command(b"[1]")["err"], "not_an_object")
        ping = self.command({"cmd": "ping"})
        self.assertTrue(ping["ok"])
        listing = self.command({"id": "c6", "cmd": "list"})
        self.assertEqual(listing["tags"], ["ai.fuel", "ai.oiltemp", "ai.rpm", "di.estop", "do.horn", "do.pump"])
        self.assertEqual(self.command({"id": "c7", "cmd": "pulse", "tag": "do.horn", "ms": 0})["err"], "bad_value")

    def test_pulse(self):
        self.start()
        self.assertTrue(self.command({"id": "p", "cmd": "pulse", "tag": "do.horn", "ms": 300})["ok"])
        self.assertIs(self.latest_frame()["tags"]["do.horn"], True)
        time.sleep(0.6)
        self.assertIs(self.latest_frame()["tags"]["do.horn"], False)

    def test_no_ack_without_id(self):
        self.start()
        self.client.sendto(json.dumps({"cmd": "set", "tag": "do.pump", "value": True}).encode(),
                           ("127.0.0.1", self.cmd_port))
        self.client.settimeout(0.5)
        with self.assertRaises(socket.timeout):
            self.client.recvfrom(65536)
        self.assertIs(self.latest_frame()["tags"]["do.pump"], True)

    def test_subscribe(self):
        self.start()
        self.assertTrue(self.command({"id": "s", "cmd": "subscribe", "ttl": 5})["ok"])
        frame = None
        deadline = time.monotonic() + 3
        while time.monotonic() < deadline:
            msg = json.loads(self.client.recvfrom(65536)[0])
            if msg.get("t") == "tags":
                frame = msg
                break
        self.assertIsNotNone(frame)
        self.assertTrue(self.command({"id": "u", "cmd": "unsubscribe"})["ok"])

    def test_frames_limit_and_sigterm(self):
        proc = subprocess.Popen(
            [sys.executable, self.script, "--listen", f"127.0.0.1:{self.cmd_port}",
             "--sink", f"127.0.0.1:{self.sink.getsockname()[1]}", "--period", "0.02", "--frames", "5"],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        self.assertEqual(proc.wait(timeout=10), 0)
        # Drop the finished run's frames, or start() takes one of them as
        # proof the new process is up and signals it before its handler exists.
        self.sink.setblocking(False)
        try:
            while True:
                self.sink.recvfrom(65536)
        except BlockingIOError:
            pass
        self.sink.settimeout(3)
        proc = self.start()
        proc.send_signal(signal.SIGTERM)
        self.assertEqual(proc.wait(timeout=10), 0)


if __name__ == "__main__":
    unittest.main()
