"""ui/python/fx/avatar.py -- Bot Avatars: an animated agent face.

FROZEN CONTRACT (UI FX swarm, 2026-09-23). Owner: W-C. Port of libdev
packages/bot-avatars (canvas 2D: draw.ts, engine.ts, shapes.ts, color.ts,
presets.ts; the React Native Skia port in ports/react-native maps nearly
1:1 onto QGradient). Shading: the 'smooth' mode (17 depth slices of the
outline, the multiply shadow and white highlight radial overlays) and
'crisp' -- NOT 'plastic', which needs per-texel numpy work the packaged
Studio does not ship. The face (eyes: open / shut / laugh / sleep lids,
blink, darts, gaze) and the engine's idle motion (wander, breathing, jelly,
blinks, the working-state hops, the sleeping nod) are ported; the pointer
follow is optional (enable with interactive=True, uses mouse tracking);
clicks call poke() (a hop). Canvas-to-Qt: an affine (a,b,c,d,e,f) is
QTransform(a,b,c,d,e,f); SVG endpoint arcs need a small converter (or
rebuild the shape from the generator formulas in scripts/gen-shapes.mjs).

The widget is square; the body occupies size / 1.5 of it (OVERSCAN 1.5, as
the source) so hops and spins stay inside.
"""
from __future__ import annotations

import math
import re

from PySide6.QtCore import QPointF, QRectF, Qt
from PySide6.QtGui import QColor, QImage, QLinearGradient, QPainter, QPainterPath, QPen, QRadialGradient, QTransform

from ui.python.fx import FxWidget, animations_enabled

# At least these seven shapes; the others are welcome.
SHAPES = ("clover", "flower", "circle", "blob", "square", "droid", "ghost",
          "drop", "star", "mech", "alien", "hexagon", "cat", "cloud",
          "pill", "pebble", "puddle")
AVATAR_STATES = ("default", "working", "sleeping")
PRESET_COLOURS = {"clover": "#35B8FF", "flower": "#2FCB7A", "circle": "#9A62FF",
                  "blob": "#2FCB7A", "square": "#35B8FF", "droid": "#D5DBEA",
                  "ghost": "#F4F2FA",
                  "triangle": "#DC48FF", "drop": "#1ED3C6", "star": "#FFD32B",
                  "mech": "#95A6C4", "alien": "#9BE85A", "hexagon": "#FF2A2A",
                  "cat": "#FF8C42", "cloud": "#CFE6FF", "pill": "#7B77F0",
                  "pebble": "#2FCB7A", "puddle": "#FF2A2A"}

# presets.ts: where the face sits on each body (faceX, faceY, faceScale).
_FACE = {"clover": (50, 50, 1), "flower": (50, 51, 0.95), "triangle": (50, 61, 0.9),
         "square": (50, 50, 1), "blob": (49.5, 50, 1), "ghost": (50, 48, 0.95),
         "circle": (50, 50, 1), "drop": (50, 62, 0.9), "star": (50, 52, 0.82),
         "droid": (50, 60, 0.95), "mech": (50, 59, 1), "alien": (50, 45, 1.05),
         "hexagon": (50, 50, 0.95), "cat": (50, 58, 1), "cloud": (50, 58, 0.95),
         "pill": (50, 50, 0.9), "pebble": (50, 50, 0.95), "puddle": (50, 50, 0.95)}

# ------------------------------------------------------------------ shapes
# shapes.ts, generated by scripts/gen-shapes.mjs. The arc / Bezier outlines
# are kept as their SVG path data; the sampled ones (squircle, polar blobs)
# are rebuilt from the generator's formulas below.

_SVG_PATHS = {
    'clover': (
        'M26.53 22.38A25 25 0 0 1 73.47 22.38A7 7 0 0 0 77.62 26.53A25 25 0 0 1 77.62 73.47'
        'A7 7 0 0 0 73.47 77.62A25 25 0 0 1 26.53 77.62A7 7 0 0 0 22.38 73.47'
        'A25 25 0 0 1 22.38 26.53A7 7 0 0 0 26.53 22.38Z'),
    'flower': (
        'M31.2 19.82A20.5 20.5 0 0 1 68.8 19.82A5 5 0 0 0 72.9 22.8'
        'A20.5 20.5 0 0 1 84.51 58.55A5 5 0 0 0 82.95 63.37A20.5 20.5 0 0 1 52.54 85.47'
        'A5 5 0 0 0 47.46 85.47A20.5 20.5 0 0 1 17.05 63.37A5 5 0 0 0 15.49 58.55'
        'A20.5 20.5 0 0 1 27.1 22.8A5 5 0 0 0 31.2 19.82Z'),
    'triangle': (
        'M38.75 27.43A13 13 0 0 1 61.25 27.43L82.7 64.49A13 13 0 0 1 71.45 84L28.55 84'
        'A13 13 0 0 1 17.3 64.49L38.75 27.43Z'),
    'ghost': (
        'M17 50C17 31.78 31.78 17 50 17C68.22 17 83 31.78 83 50V81.5Q72 93.5 61 81.5'
        'Q50 93.5 39 81.5Q28 93.5 17 81.5Z'),
    'circle': 'M50 8A42 42 0 1 1 50 92A42 42 0 1 1 50 8Z',
    'drop': (
        'M50 8.5C52.2 8.5 53.4 10.3 56.4 15.2C62.9 25.5 84 44.6 84 61.5C84 80.3 68.8 92 50 92'
        'C31.2 92 16 80.3 16 61.5C16 44.6 37.1 25.5 43.6 15.2C46.6 10.3 47.8 8.5 50 8.5Z'),
    'star': (
        'M45.77 9.7A5 5 0 0 1 54.23 9.7L65.02 26.81A4 4 0 0 0 67.42 28.55L87.02 33.53'
        'A5 5 0 0 1 89.63 41.57L76.7 57.12A4 4 0 0 0 75.78 59.94L77.11 80.12'
        'A5 5 0 0 1 70.26 85.09L51.48 77.59A4 4 0 0 0 48.52 77.59L29.74 85.09'
        'A5 5 0 0 1 22.89 80.12L24.22 59.94A4 4 0 0 0 23.3 57.12L10.37 41.57'
        'A5 5 0 0 1 12.98 33.53L32.58 28.55A4 4 0 0 0 34.98 26.81L45.77 9.7Z'),
    'droid': (
        'M16 50C16 38.95 24.95 30 36 30H64C75.05 30 84 38.95 84 50V70C84 81.05 75.05 90 64 90'
        'H36C24.95 90 16 81.05 16 70ZM4 62A7 7 0 1 1 18 62A7 7 0 1 1 4 62ZM82 62'
        'A7 7 0 1 1 96 62A7 7 0 1 1 82 62Z'),
    'mech': (
        'M10 48C10 38.06 18.06 30 28 30H72C81.94 30 90 38.06 90 48V70C90 79.94 81.94 88 72 88'
        'H28C18.06 88 10 79.94 10 70ZM3 54C3 51.79 4.79 50 7 50H11V72H7C4.79 72 3 70.21 3 68Z'
        'M89 50H93C95.21 50 97 51.79 97 54V68C97 70.21 95.21 72 93 72H89Z'),
    'alien': 'M50 10C70 10 83 27 83 46C83 65 64 92 50 92C36 92 17 65 17 46C17 27 30 10 50 10Z',
    'hexagon': (
        'M91.4 45.5A9 9 0 0 1 91.4 54.5L74.6 83.61A9 9 0 0 1 66.8 88.11L33.2 88.11'
        'A9 9 0 0 1 25.4 83.61L8.6 54.5A9 9 0 0 1 8.6 45.5L25.4 16.39A9 9 0 0 1 33.2 11.89'
        'L66.8 11.89A9 9 0 0 1 74.6 16.39L91.4 45.5Z'),
    'cat': (
        'M50 20A36 36 0 1 1 50 92A36 36 0 1 1 50 20ZM24.72 44.64A4.5 4.5 0 0 1 17.35 40.67'
        'L20.21 16.66A4.5 4.5 0 0 1 26.86 13.26L42.3 21.83A4.5 4.5 0 0 1 43.02 29.21'
        'L24.72 44.64ZM82.65 40.67A4.5 4.5 0 0 1 75.28 44.64L56.98 29.21'
        'A4.5 4.5 0 0 1 57.7 21.83L73.14 13.26A4.5 4.5 0 0 1 79.79 16.66L82.65 40.67Z'),
    'cloud': (
        'M19 44A25 25 0 1 1 69 44A25 25 0 1 1 19 44ZM47 50A21 21 0 1 1 89 50'
        'A21 21 0 1 1 47 50ZM7 68A17 17 0 1 1 41 68A17 17 0 1 1 7 68ZM32 73A18 18 0 1 1 68 73'
        'A18 18 0 1 1 32 73ZM60 70A16 16 0 1 1 92 70A16 16 0 1 1 60 70Z'),
    'pill': (
        'M28 28H72C84.15 28 94 37.85 94 50C94 62.15 84.15 72 72 72H28C15.85 72 6 62.15 6 50'
        'C6 37.85 15.85 28 28 28Z'),
}
_SVG_PARTS = {
    'droid': 'M47.5 14H52.5V32H47.5ZM43 11A7 7 0 1 1 57 11A7 7 0 1 1 43 11Z',
    'mech': 'M19.5 32L24.5 32L17 13L12 13ZM75.5 32L80.5 32L88 13L83 13ZM10 11.5A4.5 4.5 0 1 1 19 11.5A4.5 4.5 0 1 1 10 11.5ZM81 11.5A4.5 4.5 0 1 1 90 11.5A4.5 4.5 0 1 1 81 11.5Z',
}

_TOKEN = re.compile(r"[MLHVCQAZ]|-?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?")


def _arc_to(path: QPainterPath, x1, y1, r, large, sweep, x2, y2):
    """An SVG endpoint arc (circular, unrotated) onto a QPainterPath."""
    hx, hy = (x1 - x2) / 2, (y1 - y2) / 2
    d2 = hx * hx + hy * hy
    if d2 == 0:
        return
    r = max(r, math.sqrt(d2))
    coef = math.sqrt(max(0.0, (r * r - d2) / d2))
    if large == sweep:
        coef = -coef
    cx = coef * hy + (x1 + x2) / 2
    cy = coef * -hx + (y1 + y2) / 2
    a0 = math.atan2(y1 - cy, x1 - cx)
    a1 = math.atan2(y2 - cy, x2 - cx)
    da = a1 - a0
    if sweep and da < 0:
        da += 2 * math.pi
    elif not sweep and da > 0:
        da -= 2 * math.pi
    # Qt's angles run counter-clockwise on screen (y down): negate.
    path.arcTo(QRectF(cx - r, cy - r, 2 * r, 2 * r), -math.degrees(a0), -math.degrees(da))


def _svg_path(d: str) -> QPainterPath:
    """Absolute M L H V C Q A Z, as gen-shapes.mjs writes them."""
    path = QPainterPath()
    path.setFillRule(Qt.WindingFill)
    toks = _TOKEN.findall(d)
    i, cmd = 0, None
    x = y = sx = sy = 0.0

    def num():
        nonlocal i
        i += 1
        return float(toks[i - 1])

    while i < len(toks):
        if toks[i].isalpha():
            cmd = toks[i]
            i += 1
        if cmd == "M":
            x, y = num(), num()
            sx, sy = x, y
            path.moveTo(x, y)
            cmd = "L"
        elif cmd == "L":
            x, y = num(), num()
            path.lineTo(x, y)
        elif cmd == "H":
            x = num()
            path.lineTo(x, y)
        elif cmd == "V":
            y = num()
            path.lineTo(x, y)
        elif cmd == "C":
            c1x, c1y, c2x, c2y, x, y = (num() for _ in range(6))
            path.cubicTo(c1x, c1y, c2x, c2y, x, y)
        elif cmd == "Q":
            cx, cy, x, y = (num() for _ in range(4))
            path.quadTo(cx, cy, x, y)
        elif cmd == "A":
            rx, _ry, _rot, large, sweep, nx, ny = (num() for _ in range(7))
            _arc_to(path, x, y, rx, int(large), int(sweep), nx, ny)
            x, y = nx, ny
        elif cmd == "Z":
            path.closeSubpath()
            x, y = sx, sy
            cmd = None
        else:
            raise ValueError(f"bad path data near token {i}: {d[:40]}")
    return path


def _smooth_closed(pts) -> QPainterPath:
    """Catmull-Rom through the points as cubics (gen-shapes smoothClosed)."""
    path = QPainterPath()
    path.setFillRule(Qt.WindingFill)
    n = len(pts)
    path.moveTo(*pts[0])
    for i in range(n):
        p0, p1, p2, p3 = pts[(i - 1) % n], pts[i], pts[(i + 1) % n], pts[(i + 2) % n]
        path.cubicTo(p1[0] + (p2[0] - p0[0]) / 6, p1[1] + (p2[1] - p0[1]) / 6,
                     p2[0] - (p3[0] - p1[0]) / 6, p2[1] - (p3[1] - p1[1]) / 6, p2[0], p2[1])
    path.closeSubpath()
    return path


def _squircle(half, n, steps=64):
    pts = []
    for i in range(steps):
        a = i / steps * 2 * math.pi
        c, s = math.cos(a), math.sin(a)
        pts.append((50 + half * math.copysign(abs(c) ** (2 / n), c) if c else 50.0,
                    50 + half * math.copysign(abs(s) ** (2 / n), s) if s else 50.0))
    return _smooth_closed(pts)


def _blob(fn, steps=48):
    pts = []
    for i in range(steps):
        a = i / steps * 2 * math.pi
        r = fn(a)
        pts.append((50 + r * math.cos(a), 50 + r * math.sin(a)))
    return _smooth_closed(pts)


_BUILT = {
    "square": lambda: _squircle(43, 3.4),
    "blob": lambda: _blob(lambda a: 39 + 3.2 * math.sin(2 * a + 0.9) + 2.4 * math.sin(3 * a + 2.3)
                          + 1.6 * math.sin(5 * a + 0.4)),
    "pebble": lambda: _blob(lambda a: 36 + 7 * math.cos(2 * a) + 1.8 * math.sin(3 * a + 1.1)),
    "puddle": lambda: _blob(lambda a: 38 - 4 * math.cos(2 * a) + 2.8 * math.sin(3 * a + 0.5)),
}
_path_cache: dict = {}


def shape_path(shape: str) -> QPainterPath:
    """The body outline in the source's 100 x 100 design box (centre 50,50),
    filled with Qt.WindingFill. ValueError for an unknown shape."""
    if shape not in _path_cache:
        if shape in _BUILT:
            _path_cache[shape] = _BUILT[shape]()
        elif shape in _SVG_PATHS:
            _path_cache[shape] = _svg_path(_SVG_PATHS[shape])
        else:
            raise ValueError(f"unknown avatar shape {shape!r}; one of {', '.join(SHAPES)}")
    return QPainterPath(_path_cache[shape])


def _parts_path(shape: str):
    """The thin parts (antennae) of a shape, or None."""
    key = shape + ":parts"
    if key not in _path_cache:
        _path_cache[key] = _svg_path(_SVG_PARTS[shape]) if shape in _SVG_PARTS else None
    return _path_cache[key]


# ------------------------------------------------------------------ colour
# color.ts: HSL shades.

def _rgb_to_hsl(r, g, b):
    r, g, b = r / 255, g / 255, b / 255
    mx, mn = max(r, g, b), min(r, g, b)
    l = (mx + mn) / 2
    if mx == mn:
        return 0.0, 0.0, l
    d = mx - mn
    s = d / (2 - mx - mn) if l > 0.5 else d / (mx + mn)
    if mx == r:
        h = (g - b) / d + (6 if g < b else 0)
    elif mx == g:
        h = (b - r) / d + 2
    else:
        h = (r - g) / d + 4
    return h / 6, s, l


def _hsl(color) -> tuple:
    """(h 0..1, s, l) of a colour (str / QColor / (h, s, l) passes through)."""
    if isinstance(color, tuple):
        return color
    c = QColor(color)
    return _rgb_to_hsl(c.red(), c.green(), c.blue())


def _clamp01(v):
    return 0.0 if v < 0 else 1.0 if v > 1 else v


def _shade(color, dl, ds=0.0) -> tuple:
    """shade(): lightness by dl, saturation by ds; darker gets a touch richer."""
    h, s, l = _hsl(color)
    return h, _clamp01(s + ds + (-dl * 0.25 if dl < 0 else 0)), _clamp01(l + dl)


def _mix(a, b, t) -> tuple:
    """mixCss(): interpolate the hsl numbers (hue linearly, as the source)."""
    return tuple(x + (y - x) * t for x, y in zip(a, b))


def _qcolor(hsl, alpha=1.0) -> QColor:
    return QColor.fromHslF(hsl[0] % 1.0, _clamp01(hsl[1]), _clamp01(hsl[2]), alpha)


def _luminance(c: QColor) -> float:
    def lin(v):
        x = v / 255
        return x / 12.92 if x <= 0.03928 else ((x + 0.055) / 1.055) ** 2.4
    return 0.2126 * lin(c.red()) + 0.7152 * lin(c.green()) + 0.0722 * lin(c.blue())


_DARK_INK, _LIGHT_INK = QColor("#1E1A33"), QColor("#F7F5F2")

# ------------------------------------------------------------------ renderer
# draw.ts constants.
OVERSCAN = 1.5
_RISE = 0.1
_SLICES = 17
_HALF_DEPTH = 15
_CAP = 0.9
_EYE_GAP = 25
_EYE_RX = 6.3
_EYE_Y = 1
_EYE_STEPS = 8
_FACE_R = 30
# types.ts defaults (saturation 1.5 -> the body is shade(color, 0, +0.25)).
_SHADOW, _HIGHLIGHT, _DEPTH, _LIGHT, _RIM, _SPREAD = 0.35, 1.3, 0.65, 265.0, 0.5, 1.55
_PARTS_DEPTH = 0.4


def _profile(z, cap):
    return cap + (1 - cap) * math.sqrt(max(0.0, 1 - z * z))


class _Palette:
    """draw.ts palette(): the slice colours far -> near, the crisp gradients."""

    def __init__(self, base):
        shadow, highlight = _SHADOW, _HIGHLIGHT
        far = _shade(base, -0.3 * shadow, 0.05 * shadow)
        near = _shade(base, -0.12 * shadow, 0.03 * shadow)
        self.smooth, self.crisp = [], []
        for j in range(_SLICES):
            t = j / (_SLICES - 1)
            self.smooth.append(_qcolor(base if t >= 0.5 else _mix(far, base, t / 0.5)))
            self.crisp.append(None if t > 0.6 else _qcolor(_mix(far, near, t / 0.6)))
        self.base = _qcolor(base)
        self.near = _qcolor(near)
        self.light = _qcolor(_shade(base, 0.04 * highlight))
        self.dark = _qcolor(_shade(base, -0.3 * shadow, 0.05 * shadow))
        self.cap_top = _qcolor(_shade(base, 0.035 * highlight))
        self.cap_bottom = _qcolor(_shade(base, -0.035 * shadow))


_eye_cache: dict = {}


def _eye_path(x0, y0, cy) -> QPainterPath:
    """The eye's quadratic (-x0,y0) .. (0,cy) .. (x0,y0) as a short polyline."""
    qx, qy, qc = round(x0 * 50), round(y0 * 50), round(cy * 50)
    key = (qx, qy, qc)
    p = _eye_cache.get(key)
    if p is None:
        ax, ay, ac = qx / 50, qy / 50, qc / 50
        p = QPainterPath(QPointF(-ax, ay))
        for i in range(1, _EYE_STEPS + 1):
            t = i / _EYE_STEPS
            mt = 1 - t
            p.lineTo(mt * mt * -ax + t * t * ax, (mt * mt + t * t) * ay + 2 * mt * t * ac)
        if len(_eye_cache) > 256:
            _eye_cache.clear()
        _eye_cache[key] = p
    return p


def _on_sphere(x, y, yaw, pitch):
    lon = math.asin(max(-1.0, min(1.0, x / _FACE_R))) + yaw
    lat = math.asin(max(-1.0, min(1.0, -y / _FACE_R))) + pitch
    cl = math.cos(lat)
    return _FACE_R * math.sin(lon) * cl, -_FACE_R * math.sin(lat), math.cos(lon), cl, math.cos(lon) * cl


def _draw(p: QPainter, full: float, pose: dict, body_path: QPainterPath, parts, pal: _Palette,
          ink: QColor, face: tuple, shading: str) -> None:
    """draw.ts draw(): the slice stack, the smooth overlays, the face.
    `p` paints onto a transparent layer the size of the widget."""
    box = full / OVERSCAN
    S = box / 100
    half_depth = _HALF_DEPTH * _DEPTH
    cap = 1 - (1 - _CAP) * _RIM
    la = math.radians(_LIGHT)
    lx, ly = math.sin(la), -math.cos(la)

    cy0, sy = math.cos(pose["yaw"]), math.sin(pose["yaw"])
    cp0, sp = math.cos(pose["pitch"]), math.sin(pose["pitch"])
    facing = cy0 * cp0

    def floor(v):
        return (-0.22 if v < 0 else 0.22) if abs(v) < 0.22 else v
    cy, cp = floor(cy0), floor(cp0)

    cr, sr = math.cos(pose["roll"]), math.sin(pose["roll"])
    kx, ky = pose["sx"] * S, pose["sy"] * S
    lift = 50 * (1 - pose["sy"]) * S
    body = QTransform(cr * kx, sr * kx, -sr * ky, cr * ky,
                      full / 2 + pose["x"] * S - sr * lift,
                      full / 2 + _RISE * box + pose["y"] * S + cr * lift)

    def slice_t(z, s):
        m0, m1, m3 = cy * s, sy * sp * s, cp * s
        e = z * sy * half_depth - 50 * m0
        fo = -z * cy * sp * half_depth - 50 * m1 - 50 * m3
        return QTransform(m0, m1, 0.0, m3, e, fo) * body

    p.setPen(Qt.NoPen)
    soft = shading != "crisp"
    if not soft:
        lit = QLinearGradient(lx * 56, ly * 56, -lx * 56, -ly * 56)
        lit.setColorAt(0, pal.light)
        lit.setColorAt(0.45, pal.near)
        lit.setColorAt(1, pal.dark)
        capg = QLinearGradient(lx * 46, ly * 46, -lx * 46, -ly * 46)
        capg.setColorAt(0, pal.cap_top)
        capg.setColorAt(1, pal.cap_bottom)

    def solid(path, hd):
        order = 1 if facing >= 0 else -1
        for j in range(_SLICES):
            k = j if order > 0 else _SLICES - 1 - j
            z = -1 + 2 * k / (_SLICES - 1)
            s = _profile(z, cap)
            m0, m1, m3 = cy * s, sy * sp * s, cp * s
            e = z * sy * hd - 50 * m0
            fo = -z * cy * sp * hd - 50 * m1 - 50 * m3
            t = QTransform(m0, m1, 0.0, m3, e, fo) * body
            p.setTransform(t)
            if soft:
                p.setBrush(pal.smooth[j])
            else:
                near = j / (_SLICES - 1)
                if j == _SLICES - 1:
                    brush = capg
                elif near > 0.6:
                    brush = lit
                else:
                    brush = pal.crisp[j]
                p.setBrush(brush)
            p.drawPath(path)

    if parts is not None:
        solid(parts, half_depth * _PARTS_DEPTH)
    solid(body_path, half_depth)

    if soft:
        # The soft shadow (lower right) and light (upper left) over the whole
        # form. The source clips to the union of the slices and multiplies the
        # shadow; on a layer holding only the body, SourceAtop is that clip,
        # and multiplying by black at alpha a is painting black at alpha a.
        p.setTransform(body)
        p.setCompositionMode(QPainter.CompositionMode_SourceAtop)
        sa = min(1.0, 0.34 * _SHADOW)
        r0, r1 = 4 * _SPREAD, 84 * _SPREAD
        g = QRadialGradient(QPointF(-lx * 45, -ly * 45), r1)
        g.setColorAt(0, QColor.fromRgbF(0, 0, 0, sa))
        g.setColorAt(r0 / r1, QColor.fromRgbF(0, 0, 0, sa))
        g.setColorAt((r0 + 0.5 * (r1 - r0)) / r1, QColor.fromRgbF(0, 0, 0, sa * 0.35))
        g.setColorAt(1, QColor.fromRgbF(0, 0, 0, 0))
        p.fillRect(QRectF(-120, -120, 240, 240), g)
        ha = min(1.0, 0.22 * _HIGHLIGHT)
        h = QRadialGradient(QPointF(lx * 37, ly * 37), 62 * _SPREAD)
        h.setColorAt(0, QColor.fromRgbF(1, 1, 1, ha))
        h.setColorAt(0.6, QColor.fromRgbF(1, 1, 1, ha * 0.23))
        h.setColorAt(1, QColor.fromRgbF(1, 1, 1, 0))
        p.fillRect(QRectF(-120, -120, 240, 240), h)
        p.setCompositionMode(QPainter.CompositionMode_SourceOver)

    # the face, printed on the front cap: clipped to the front slice
    if facing > -0.2:
        p.save()
        zf = 1 if facing >= 0 else -1
        p.setTransform(slice_t(zf, _profile(zf, cap)))
        p.setClipPath(body_path)
        fx_, fy_, fs = face
        p.setTransform(QTransform(fs, 0, 0, fs, fx_ - 50, fy_ - 50) * body)
        _draw_face(p, pose, ink)
        p.restore()


def _draw_face(p: QPainter, pose: dict, ink: QColor) -> None:
    wd, ww, ws = pose["w"]
    half = _EYE_GAP / 2
    lx, ly = pose["lookX"], pose["lookY"]
    yaw, pitch = pose["yaw"], pose["pitch"]
    base = p.transform()

    def past(v, d):
        return 0.0 if abs(v) <= d else math.copysign(abs(v) - d, v) / (1 - d)

    def clamp1(v):
        return max(-1.0, min(1.0, v))

    up = past(clamp1(-pitch / 0.26 - ly / 7), 0.34)
    side_k = abs(past(clamp1(lx / 4.5), 0.4))
    tall = max(0.3, 1 + 0.55 * up - 0.1 * side_k)
    wide = 1 - 0.05 * up + 0.12 * side_k
    open_ = wd + ww * (1 - pose["laugh"])
    laugh = ww * pose["laugh"]
    lift = max(0.0, -pose["y"]) / 26
    sag = 0.5 + 0.5 * pose["breath"]
    pen = QPen(ink)
    pen.setCapStyle(Qt.RoundCap)
    pen.setJoinStyle(Qt.RoundJoin)
    p.setBrush(Qt.NoBrush)
    for side in (-1, 1):
        lid = pose["blinkL"] if side < 0 else pose["blinkR"]
        e = max(0.0, min(1.0, pose["eyeOpen"] * (1 - lid)))
        k_open, k_shut, k_laugh, k_sleep = open_ * e, open_ * (1 - e), laugh, ws
        x0 = k_open * 0.01 + k_shut * 5.4 + k_laugh * 6.2 + k_sleep * 6
        y0 = k_open * 1.1 * tall + k_shut * 0.6 + k_laugh * (2.2 - lift * 1.5) + k_sleep * (-1.4 + sag)
        cy = k_open * -3.3 * tall + k_shut * 0.6 + k_laugh * (-11.4 - 4 * lift) + k_sleep * (5.4 + 2 * sag)
        w = k_open * _EYE_RX * 2 * wide + k_shut * 2.8 + k_laugh * 4.4 + k_sleep * 4
        dx = lx * (k_open + 0.5 * (k_shut + k_laugh))
        dy = ly * (k_open + 0.5 * k_shut)
        qx, qy, qsx, qsy, qz = _on_sphere(side * half + dx, _EYE_Y + dy, yaw, pitch)
        if qz <= 0.02 or w <= 0.01:
            continue
        p.setOpacity(min(1.0, qz * 5))
        p.setTransform(QTransform(max(0.02, qsx), 0, 0, max(0.02, qsy), qx, qy) * base)
        pen.setWidthF(w)
        p.setPen(pen)
        p.drawPath(_eye_path(x0, y0, cy))
    p.setOpacity(1.0)


# ------------------------------------------------------------------ engine
# engine.ts: the pose simulation.

_DEG = math.pi / 180
_TAU = math.pi * 2
_HOP_T = 0.68
_HOP_SPIN_H = 26
_FLIP_PRE = 0.2
_JUMP = dict(height=_HOP_SPIN_H, time=_HOP_T, stretch=1, squash=1.15, squashTime=0.37, squashEase="pulse",
             groundTime=0.11, groundEase="pulse", riseTime=0.33, riseEase="pulse", clickSquashTime=0.24,
             spin=1, lean=6, every=8, land=0)
_SQUASH_PEAK = {"sharp": 0, "pulse": 2 / 7, "soft": 0.5, "bouncy": 0.144}
_SWITCH_TO = {"default": 1.2, "working": 0.7, "sleeping": 1.4}
_SWITCH_FROM_SLEEP = 1.0
_GAZE_YAW, _GAZE_PITCH, _GAZE_ROLL = 35 * _DEG, 14 * _DEG, 3.2 * _DEG
_GAZE_HOLD_MIN, _GAZE_HOLD_MAX = 2.6, 4.4
_REST = {"default": dict(pitch=0.0, roll=0.0, y=0.0, lookX=0.0, lookY=0.0),
         "working": dict(pitch=5 * _DEG, roll=0.0, y=0.0, lookX=0.0, lookY=0.0),
         "sleeping": dict(pitch=-16 * _DEG, roll=6 * _DEG, y=3.0, lookX=0.0, lookY=1.0)}
_M32 = 0xFFFFFFFF


def _flip_pre(j, poked):
    return j["clickSquashTime"] if poked else _FLIP_PRE * j["time"]


def _flip_duration(j, poked):
    return (_flip_pre(j, poked) + j["time"]
            + _SQUASH_PEAK[j["squashEase"]] * (j["clickSquashTime"] if poked else j["squashTime"])
            + max(0, j["groundTime"]) + j["riseTime"] + max(0, j["land"]) + 0.05)


def _rise_pulse(v, ease):
    if v <= 0:
        return 1.0
    if v >= 1:
        return 0.0
    if ease == "sharp":
        return (1 - v) * (1 - v)
    if ease == "soft":
        return 0.5 + 0.5 * math.cos(math.pi * v)
    if ease == "bouncy":
        return math.exp(-3.2 * v) * math.cos(5.4 * v) - v * v * v * 0.026
    k = 4.2 * v
    return (1 + k) * math.exp(-k) - v * v * v * 0.078


def _squash_pulse(u, ease):
    if u <= 0 or u >= 1:
        return 0.0
    if ease == "sharp":
        x = (1 - u) * (1 - u)
    elif ease == "soft":
        x = math.sin(math.pi * u) ** 2
    elif ease == "bouncy":
        x = math.exp(-3.15 * u) * math.sin(8.43 * u) / 0.596
    else:
        k = 7 * u
        x = k * k * math.exp(2 - k) / 4
    tail = 1 - (u - 0.85) / 0.15 if u > 0.85 else 1
    return x * tail * tail * (3 - 2 * tail)


def _ground_shape(v, ease):
    return 1 + 0.25 * _squash_pulse(v, ease)


def _hop_squash(a):
    return math.exp(-((min(abs(a), abs(a - 1)) / 0.11) ** 2))


def _ease_in_out(p):
    return 4 * p * p * p if p < 0.5 else 1 - (-2 * p + 2) ** 3 / 2


def _ease_sine(p):
    return 0.5 - 0.5 * math.cos(math.pi * p)


def _approach(cur, target, rate, dt):
    return cur + (target - cur) * (1 - math.exp(-rate * dt))


def _smooth(a, b, v):
    x = min(1.0, max(0.0, (v - a) / (b - a)))
    return x * x * (3 - 2 * x)


def _mulberry32(seed: int):
    """engine.ts rng(): mulberry32, bit for bit (JS int32 maths mod 2^32)."""
    state = [(seed * 0x9E3779B1) & _M32 or 1]

    def imul(a, b):
        return (a * b) & _M32

    def nxt():
        state[0] = (state[0] + 0x6D2B79F5) & _M32
        t = state[0]
        t = imul(t ^ (t >> 15), t | 1)
        t = (t ^ ((t + imul(t ^ (t >> 7), t | 61)) & _M32)) & _M32
        return ((t ^ (t >> 14)) & _M32) / 4294967296
    return nxt


class _Wander:
    """A value that drifts to a new target now and then (spring or approach)."""

    def __init__(self, rand, amp, hold_min, hold_max, rate, spring=False):
        self.rand, self.amp, self.hold_min, self.hold_max, self.rate = rand, amp, hold_min, hold_max, rate
        self.spring = spring
        self.value = self.vel = self.target = self.next = 0.0

    def update(self, t, dt):
        if t >= self.next:
            self.target = (self.rand() * 2 - 1) * self.amp
            self.next = t + self.hold_min + self.rand() * (self.hold_max - self.hold_min)
        if self.spring:
            w, z = self.rate * 1.6, 0.9
            self.vel += (w * w * (self.target - self.value) - 2 * z * w * self.vel) * dt
            self.value += self.vel * dt
        else:
            self.value = _approach(self.value, self.target, self.rate, dt)

    def aim(self, v):
        self.target = v
        self.next = math.inf

    def set(self, amp, hold_min, hold_max, rate):
        self.amp, self.hold_min, self.hold_max, self.rate = amp, hold_min, hold_max, rate
        self.next = 0.0


class _Event:
    """A one-shot: progress 0 -> 1 over its duration, then idle at -1."""

    def __init__(self, duration):
        self.duration = duration
        self.p = -1.0

    def fire(self):
        self.p = 0.0

    @property
    def active(self):
        return self.p >= 0

    def update(self, dt):
        if self.p < 0:
            return
        self.p += dt / self.duration
        if self.p >= 1:
            self.p = -1.0


def _rest_pose(state: str) -> dict:
    r = _REST[state]
    return dict(yaw=0.0, pitch=r["pitch"], roll=r["roll"], x=0.0, y=r["y"], sx=1.0, sy=1.0, eyeOpen=1.0,
                blinkL=0.0, blinkR=0.0, lookX=r["lookX"], lookY=r["lookY"], breath=0.0, laugh=0.0,
                whirl=0.0, whirlAngle=0.0, w=[1.0 if s == state else 0.0 for s in AVATAR_STATES])


class _Sim:
    """engine.ts Sim: advances a pose through time."""

    def __init__(self, seed: float, state: str = "default"):
        self.pose = _rest_pose("default")
        self.state = "default"
        self.rand = r = _mulberry32(math.floor(seed * 1e6) + 1)
        self.w_from = [1.0, 0.0, 0.0]
        self.tr, self.tr_duration = 1.0, 1.2
        self.yawW = _Wander(r, 36 * _DEG, 1.1, 2.6, 3, True)
        self.pitchW = _Wander(r, 10 * _DEG, 1.1, 2.6, 2.6, True)
        self.rollW = _Wander(r, 5 * _DEG, 1.6, 3.2, 2, True)
        self.lookXW = _Wander(r, 3.6, 0.5, 2, 14)
        self.lookYW = _Wander(r, 2.4, 0.5, 2, 14)
        self.blink = _Event(0.17)
        self.blink_again = False
        self.dart = _Event(0.12)
        self.dart_x = self.dart_y = 0.0
        self.jump = dict(_JUMP)
        self.flip = _Event(_flip_duration(self.jump, False))
        self.flip_poked = False
        self.flip_side = 1
        self.nod = _Event(1.7)
        self.hop_count = 0
        self.hop_gain = 0.0
        self.laugh_ev = _Event(0.8)
        self.prev_yaw = self.jelly = self.jelly_v = self.gaze_lead = 0.0
        self.gaze_dir = (0, 0)
        self.gaze_at = 0.0
        self.turn_k = 1.0
        self.ptr_x = self.ptr_y = self.ptr_s = 0.0
        self.ptr_tx = self.ptr_ty = self.ptr_ts = 0.0
        self.base_yaw = 0.0
        # every instance starts somewhere else in its loops
        self.t = r() * 10
        self.hop_phase = r()
        self.breath_phase = r()
        self.blink_at = self.t + 1 + r() * 3
        self.flip_at = self._next_flip(self.t, 1)
        self.nod_at = self.t + 3 + r() * 4
        self.dart_at = self.t + 1 + r() * 2
        self.laugh_at = self.t + 0.6 + r() * 1.5
        self.set_state(state, True)

    def set_state(self, nxt, immediate=False):
        if nxt == self.state and not immediate:
            return
        frm = self.state
        self.state = nxt
        w = self.pose["w"]
        if immediate:
            for i in range(3):
                w[i] = 1.0 if AVATAR_STATES[i] == nxt else 0.0
            self.tr = 1.0
        else:
            self.w_from = list(w)
            self.tr = 0.0
            self.tr_duration = _SWITCH_FROM_SLEEP if frm == "sleeping" else _SWITCH_TO[nxt]
        if nxt == "default":
            self.yawW.set(_GAZE_YAW, 2.6, 5.4, 2)
            self.pitchW.set(_GAZE_PITCH, 2.8, 5.8, 1.8)
            self.rollW.set(_GAZE_ROLL, 3.4, 6.6, 1.5)
            self.gaze_at = 0.0
            self.gaze_dir = (0, 0)
            self.lookXW.set(3.6, 0.6, 2.2, 13)
            self.lookYW.set(2.4, 0.6, 2.2, 13)
            self.flip_at = self._next_flip(self.t, 0.6)
        elif nxt == "working":
            self.yawW.set(16 * _DEG, 0.9, 1.8, 4)
            self.pitchW.set(3 * _DEG, 1.2, 2.4, 3)
            self.rollW.set(0, 1, 2, 3)
            self.lookXW.set(2, 0.5, 1.2, 12)
            self.lookYW.set(1, 0.5, 1.2, 12)
            self.hop_phase = 0.0
            self.hop_count = 0
            self.laugh_at = self.t + 0.5 + self.rand() * 1.2
        else:
            self.yawW.set(7 * _DEG, 3, 6, 0.7)
            self.pitchW.set(3 * _DEG, 3, 6, 0.7)
            self.rollW.set(2 * _DEG, 3, 6, 0.6)
            self.lookXW.set(0, 2, 4, 2)
            self.lookYW.set(0, 2, 4, 2)
            self.nod_at = self.t + 2.5 + self.rand() * 4

    def set_pointer(self, x, y, strength):
        self.ptr_tx = max(-1.2, min(1.2, x))
        self.ptr_ty = max(-1.2, min(1.2, y))
        self.ptr_ts = max(0.0, min(1.0, strength))

    def poke(self):
        if self.flip.active and self.flip.p < 0.6:
            return
        self.flip_poked = True
        self.flip.duration = _flip_duration(self.jump, True)
        self.flip_side = -1 if self.rand() < 0.5 else 1
        self.flip.fire()
        self.flip_at = self._next_flip(self.t, 1.1)

    def _next_gaze(self):
        r = self.rand
        px, py = self.gaze_dir
        if px != 0 or py != 0:
            q = r()
            if q < 0.66:
                return -px, -py
            if q < 0.85:
                return -px, py
            return 0, 0
        corners = ((1, -1), (-1, 1), (-1, -1), (1, 1))
        return corners[int(math.floor(r() * 4))]

    def _next_flip(self, t, k):
        every = self.jump["every"]
        return t + every * k * (0.625 + self.rand() * 0.75) if every > 0 else math.inf

    def update(self, dt):  # noqa: C901 -- a straight port of Sim.update
        dt = min(dt, 0.05)
        self.t += dt
        t = self.t
        p = self.pose
        w = p["w"]
        if self.tr < 1:
            self.tr = min(1.0, self.tr + dt / self.tr_duration)
            e = _ease_sine(self.tr)
            for i in range(3):
                target = 1.0 if AVATAR_STATES[i] == self.state else 0.0
                w[i] = self.w_from[i] + (target - self.w_from[i]) * e
        wd, ww, ws = w

        rest = dict(pitch=0.0, roll=0.0, y=0.0, lookX=0.0, lookY=0.0)
        for i in range(3):
            r = _REST[AVATAR_STATES[i]]
            for key in rest:
                rest[key] += r[key] * w[i]

        if self.state == "default" and t >= self.gaze_at:
            gx, gy = self.gaze_dir = self._next_gaze()
            reach = 0.84 + self.rand() * 0.16
            self.yawW.aim(gx * _GAZE_YAW * reach * self.turn_k)
            self.pitchW.aim(gy * _GAZE_PITCH * reach)
            self.rollW.aim(gx * _GAZE_ROLL * reach * self.turn_k)
            self.gaze_at = t + _GAZE_HOLD_MIN + self.rand() * (_GAZE_HOLD_MAX - _GAZE_HOLD_MIN)

        for wander in (self.yawW, self.pitchW, self.rollW, self.lookXW, self.lookYW):
            wander.update(t, dt)

        self.ptr_s = _approach(self.ptr_s, self.ptr_ts, 8, dt)
        self.ptr_x = _approach(self.ptr_x, self.ptr_tx, 14, dt)
        self.ptr_y = _approach(self.ptr_y, self.ptr_ty, 14, dt)
        ps = self.ptr_s
        quiet = 1 - 0.75 * ps

        self.base_yaw = _approach(self.base_yaw, self.yawW.value * quiet + 22 * _DEG * self.ptr_x * ps, 5, dt)
        base_pitch = rest["pitch"] + self.pitchW.value * quiet - 12 * _DEG * self.ptr_y * ps
        base_roll = rest["roll"] + self.rollW.value * quiet
        base_y = rest["y"]
        base_look_x = rest["lookX"] + self.lookXW.value * quiet + 4.5 * self.ptr_x * ps
        base_look_y = rest["lookY"] + self.lookYW.value * quiet + 3 * self.ptr_y * ps

        spin = hop_y = pitch_add = roll_add = blink_close = look_x_add = look_y_add = laugh = 0.0
        sx = sy = 1.0
        whirl = whirl_angle = 0.0

        def envelope(q):
            return _smooth(0.1, 0.26, q) * (1 - _smooth(0.66, 0.9, q))

        def ring_angle(q):
            return _TAU * (1.5 * q + 0.9 * _ease_in_out(q))

        # blinks, with a double blink now and then
        if t >= self.blink_at and not self.blink.active and wd + ww > 0.5:
            self.blink.fire()
            self.blink_again = (not self.blink_again) and self.rand() < 0.22
            self.blink_at = t + (0.28 if self.blink_again else 2.2 + self.rand() * 2.6)
        self.blink.update(dt)
        if self.blink.active:
            blink_close = math.sin(math.pi * self.blink.p)

        # eye darts
        if t >= self.dart_at and not self.dart.active and wd + ww > 0.5:
            self.dart.fire()
            self.dart_x = (self.rand() * 2 - 1) * 4
            self.dart_y = (self.rand() * 2 - 1) * 2
            self.dart.duration = 0.25 + self.rand() * 0.45
            self.dart_at = t + 1.2 + self.rand() * 2.6
        self.dart.update(dt)
        if self.dart.active:
            q = self.dart.p
            hold = q / 0.15 if q < 0.15 else (1 - q) / 0.2 if q > 0.8 else 1
            look_x_add += self.dart_x * hold * (wd + ww)
            look_y_add += self.dart_y * hold * (wd + ww)

        # idle: a full turn now and then, with a jump (also a poke's)
        if self.state == "default" and t >= self.flip_at and not self.flip.active:
            self.flip_poked = False
            self.flip.duration = _flip_duration(self.jump, False)
            self.flip_side = -1 if self.rand() < 0.5 else 1
            self.flip.fire()
            self.flip_at = self._next_flip(t, 1)
        self.flip.update(dt)
        J = self.jump
        if self.flip.active:
            pre_s = _flip_pre(J, self.flip_poked)
            a = (self.flip.p * self.flip.duration - pre_s) / J["time"]
            q = min(1.0, max(0.0, a))
            arc = math.sin(math.pi * q)
            spin += _TAU * J["spin"] * _ease_in_out(q)
            hop_y -= J["height"] * arc
            tl = (a - 1) * J["time"] - J["land"]
            squash_time = J["clickSquashTime"] if self.flip_poked else J["squashTime"]
            hold_t = max(0, J["groundTime"])
            peak_t = _SQUASH_PEAK[J["squashEase"]] * squash_time
            rise = tl - peak_t - hold_t
            if tl <= peak_t:
                depth = _squash_pulse(tl / squash_time, J["squashEase"])
            elif rise <= 0:
                depth = _ground_shape((tl - peak_t) / hold_t, J["groundEase"])
            else:
                depth = _rise_pulse(rise / J["riseTime"], J["riseEase"])
            if a < 0:
                u = max(0.0, 1 + a * J["time"] / pre_s)
                land = u * u * (3 - 2 * u) if self.flip_poked else _hop_squash(u - 1)
            elif tl > 0:
                land = depth
            elif a < 0.2:
                land = _hop_squash(a)
            else:
                land = 0.0
            land *= J["squash"]
            sx += 0.16 * land - 0.06 * arc * J["stretch"]
            sy += -0.18 * land + 0.09 * arc * J["stretch"]
            roll_add += self.flip_side * J["lean"] * _DEG * arc
            if J["spin"] > 0:
                laugh = max(laugh, arc)
                whirl = max(whirl, envelope(q))
                whirl_angle = ring_angle(q)

        # working: hops all the time; every third one spins
        exit_hold = max(0, J["groundTime"])
        exit_for = exit_hold + J["riseTime"]
        if self.state == "working":
            self.hop_gain = ww
        if self.hop_gain > 0.02 and (self.state == "working" or self.hop_phase > 0):
            self.hop_phase += dt / _HOP_T
            if self.hop_phase >= 1:
                if self.state == "working":
                    self.hop_phase -= 1
                    self.hop_count += 1
                elif (self.hop_phase - 1) * _HOP_T >= exit_for:
                    self.hop_phase = 0.0
                    self.hop_gain = 0.0
            g = self.hop_gain
            q = min(1.0, self.hop_phase)
            arc = math.sin(math.pi * q)
            spinning = self.hop_count % 3 == 2
            h = _HOP_SPIN_H if spinning else 18
            hop_y -= h * arc * g
            exit_t = (self.hop_phase - 1) * _HOP_T if self.state != "working" and self.hop_phase > 1 else -1
            if exit_t < 0:
                land = _hop_squash(self.hop_phase)
            elif exit_t < exit_hold:
                land = _ground_shape(exit_t / exit_hold, J["groundEase"])
            else:
                land = _rise_pulse((exit_t - exit_hold) / J["riseTime"], J["riseEase"])
            sx += (0.16 * land - 0.06 * arc) * g
            sy += (-0.18 * land + 0.09 * arc) * g
            if spinning:
                spin += _TAU * _ease_in_out(q) * g
                laugh = max(laugh, arc * g)
                if envelope(q) * g > whirl:
                    whirl = envelope(q) * g
                    whirl_angle = ring_angle(q)
            roll_add += (1 if self.hop_count % 2 == 0 else -1) * 6 * _DEG * arc * g

        # working: now and then a laugh shuts the eyes into arcs
        if self.state == "working" and t >= self.laugh_at and not self.laugh_ev.active:
            self.laugh_ev.fire()
            self.laugh_ev.duration = 0.6 + self.rand() * 0.5
            self.laugh_at = t + 1.6 + self.rand() * 2.2
        self.laugh_ev.update(dt)
        if self.laugh_ev.active:
            q = self.laugh_ev.p
            laugh = max(laugh, q / 0.18 if q < 0.18 else (1 - q) / 0.22 if q > 0.78 else 1)

        # sleeping: the head drops, then jerks back up
        if self.state == "sleeping" and t >= self.nod_at and not self.nod.active:
            self.nod.fire()
            self.nod_at = t + 4 + self.rand() * 4
        self.nod.update(dt)
        if self.nod.active:
            q = self.nod.p
            dip = _ease_in_out(q / 0.72) if q < 0.72 else 1 - _ease_in_out((q - 0.72) / 0.28)
            pitch_add -= 13 * _DEG * dip * ws

        # breathing, deeper and slower asleep
        self.breath_phase += dt / (3.6 + 1.2 * ws)
        breath = math.sin(self.breath_phase * _TAU)
        p["breath"] = breath
        sx += breath * (0.008 + 0.014 * ws)
        sy += breath * (0.012 + 0.02 * ws)
        bob = math.sin(t * _TAU / 3.4) * 2 * (1 - ws)

        # compose
        p["yaw"] = self.base_yaw + spin
        dyaw = self.base_yaw - self.prev_yaw
        dyaw = (dyaw + math.pi) % _TAU - math.pi
        self.prev_yaw = self.base_yaw
        rate = abs(dyaw) / dt if dt > 0 else 0.0
        lead_target = max(-2.2, min(2.2, dyaw / dt * 2.4)) if dt > 0 else 0.0
        self.gaze_lead = _approach(self.gaze_lead, lead_target, 9, dt)
        jelly_target = min(0.22, 0.055 * rate)
        omega, zeta = 16, 0.45
        self.jelly_v += (omega * omega * (jelly_target - self.jelly) - 2 * zeta * omega * self.jelly_v) * dt
        self.jelly += self.jelly_v * dt
        jelly = max(-0.08, min(0.28, self.jelly)) * 0.6
        sx *= 1 + jelly
        sy *= 1 - 0.55 * jelly

        p["pitch"] = base_pitch + pitch_add
        p["roll"] = base_roll + roll_add
        p["x"] = 0.0
        p["y"] = base_y + hop_y + bob
        p["sx"] = sx
        p["sy"] = sy
        p["eyeOpen"] = 1.0
        p["laugh"] = _approach(p["laugh"], laugh, 30, dt)
        p["blinkL"] = blink_close
        p["blinkR"] = blink_close
        p["lookX"] = base_look_x + look_x_add + self.gaze_lead
        p["lookY"] = base_look_y + look_y_add
        p["whirl"] = whirl
        p["whirlAngle"] = whirl_angle


# ------------------------------------------------------------------ widget
_REACH = 3.0      # how far the pointer's pull reaches, in head widths


class BotAvatar(FxWidget):
    """Args:
        shape: one of SHAPES (or any extra shape the port adds).
        size: the widget's side in px (the body is size / 1.5).
        state: one of AVATAR_STATES.
        color: body colour (None: the shape's preset colour).
        seed: 0..1, varies the idle motion between instances.
        interactive: follow the pointer (needs mouse tracking).
    The avatar animates while running (start/stop from FxWidget); its still
    frame is the rest pose of its state.
    """

    def __init__(self, parent=None, shape: str = "clover", size: int = 40,
                 state: str = "default", color=None, seed: float = 0.37,
                 interactive: bool = False):
        super().__init__(parent)
        if state not in AVATAR_STATES:
            raise ValueError(f"unknown avatar state {state!r}; one of {', '.join(AVATAR_STATES)}")
        self._shape = None
        self._color = color
        self._shading = "smooth"          # or "crisp"; "plastic" is not ported
        self._interactive = bool(interactive)
        self._sim = _Sim(min(1.0, max(0.0, float(seed))), state)
        self._live = False                # the sim has moved since the last still
        self._pointer = None              # widget coords while the mouse is over
        self._layer = None
        self.setFixedSize(int(size), int(size))
        self.setAttribute(Qt.WA_TranslucentBackground)
        self.setMouseTracking(self._interactive)
        self.set_shape(shape)

    def state(self) -> str:
        return self._sim.state

    def set_state(self, state: str) -> None:
        """Blend to `state` over the source's durations (to default 1.2 s,
        working 0.7 s, sleeping 1.4 s; from sleeping 1.0 s). ValueError for
        an unknown state."""
        if state not in AVATAR_STATES:
            raise ValueError(f"unknown avatar state {state!r}; one of {', '.join(AVATAR_STATES)}")
        self._sim.set_state(state)
        self.update()

    def set_shape(self, shape: str) -> None:
        body = shape_path(shape)          # ValueError for an unknown shape
        self._shape = shape
        self._body = body
        self._parts = _parts_path(shape)
        self._face = _FACE.get(shape, (50, 50, 1))
        self._recolour()
        self.update()

    def poke(self) -> None:
        """A click: a hop with a spin (ignored while one is under way)."""
        self._sim.poke()
        self.update()

    def pose(self) -> dict:
        """The current pose fields (yaw, pitch, roll, x, y, sx, sy, eyeOpen,
        blink, lookX, lookY, breath, laugh, w) -- for tests."""
        pose = dict(self._sim.pose)
        pose["w"] = list(pose["w"])
        pose["blink"] = max(pose["blinkL"], pose["blinkR"])
        return pose

    # -- internals
    def _recolour(self):
        picked = self._color if self._color is not None else PRESET_COLOURS.get(self._shape, "#35B8FF")
        body = _shade(picked, 0.0, 0.25)          # saturation 1.5
        self._palette = _Palette(body)
        self._ink = _LIGHT_INK if _luminance(_qcolor(body)) < 0.13 else _DARK_INK

    def _draw_pose(self) -> dict:
        """The pose to paint: the sim's, or the rest pose for a still frame."""
        if self._live and not (self._running and not animations_enabled()):
            return self._sim.pose
        return _rest_pose(self._sim.state)

    # -- FxWidget
    def advance(self, t: float, dt: float) -> None:
        sim = self._sim
        if self._interactive:
            if self._pointer is not None:
                full = min(self.width(), self.height())
                box = full / OVERSCAN or 1
                dx = (self._pointer.x() - self.width() / 2) / box
                dy = (self._pointer.y() - (self.height() / 2 + _RISE * box)) / box
                d = math.hypot(dx, dy)
                strength = 1.0 if d < 1 else 0.0 if d > _REACH else 1 - (d - 1) / (_REACH - 1)
                sim.set_pointer(dx / max(1.0, d), dy / max(1.0, d), strength)
            else:
                sim.set_pointer(0, 0, 0)
        sim.update(dt)
        self._live = True

    def stop(self) -> None:
        super().stop()
        self._live = False

    def paint_frame(self, painter, t: float) -> None:
        w, h = self.width(), self.height()
        full = min(w, h)
        if full <= 0:
            return
        dpr = max(1.0, painter.device().devicePixelRatioF())
        pw, ph = int(math.ceil(w * dpr)), int(math.ceil(h * dpr))
        layer = self._layer
        if layer is None or layer.width() != pw or layer.height() != ph:
            layer = self._layer = QImage(pw, ph, QImage.Format_ARGB32_Premultiplied)
        layer.setDevicePixelRatio(dpr)
        layer.fill(0)
        lp = QPainter(layer)
        try:
            lp.setRenderHint(QPainter.Antialiasing)
            if w != h:
                lp.translate((w - full) / 2, (h - full) / 2)
            _draw(lp, full, self._draw_pose(), self._body, self._parts, self._palette,
                  self._ink, self._face, self._shading)
        finally:
            lp.end()
        painter.save()
        painter.drawImage(QRectF(0, 0, w, h), layer)
        painter.restore()

    # -- Qt
    def mouseMoveEvent(self, event):
        if self._interactive:
            self._pointer = event.position()
        super().mouseMoveEvent(event)

    def leaveEvent(self, event):
        self._pointer = None
        super().leaveEvent(event)

    def mousePressEvent(self, event):
        if event.button() == Qt.LeftButton:
            self.poke()
            event.accept()
            return
        super().mousePressEvent(event)
