"""designer/ide/backend_scaffold.py -- a working backend for the design's tags.

A Studio design invents tags ("ai.rpm", "do.pump") that no hardware
publishes yet. The Code section's "Generate backend..." writes a small,
runnable backend into the project folder that speaks the panel's wire
protocol (docs/CONTRACT.md section 2) for exactly those tags, with one stub
function per tag for the user -- or the coding agent -- to fill in:

    <project>/backend/
        backend.py   standalone, Python 3.8+ standard library only
        tags.json    the tag catalogue (see render_tags_json)
        tags.h       C constants for the tag names (see render_tags_header)
        README.md    how to run it and point the panel at it

backend.py (render_backend_py) -- the generated program:
  * `TAGS`: dict {tag: {"access": "R"|"W"|"RW"|"", "writable": bool}} in
    tag order (all index.tags()).
  * One function per tag, `read_<ident>()` for every tag, returning a
    placeholder: bool tags ("di."/"do." prefixes) False, "sys.uptime"
    seconds since start, everything else 0.0. `ident` = tag_ident(tag).
  * One function per writable tag, `write_<ident>(value)`, storing the value
    so the next read returns it (the placeholder "hardware"), returning True.
  * Wire protocol, CONTRACT 2:
      - listens for commands on --listen HOST:PORT (default 127.0.0.1:5010;
        5000 belongs to hmi-hwd), one JSON object per datagram, max 8192
        bytes (larger: dropped);
      - "set" {tag, value}: unknown tag -> ack err "unknown_tag"; tag not in
        the writable set -> "not_writable"; value not bool/int/float ->
        "bad_value"; else write_<ident>(value) -> ack ok;
      - "pulse" {tag, ms}: writable check as set, ms int 1..10000 else
        "bad_value"; writes True now and False after ms (a threading.Timer),
        ack ok;
      - "subscribe" {ttl?}: adds the sender to the subscribers for ttl
        seconds (default 5, capped at 60); "unsubscribe" removes it;
      - "list": ack ok with "tags": sorted tag names;
      - "ping": ack ok;
      - anything else: "unknown_cmd"; non-JSON "bad_json"; JSON that is not
        an object "not_an_object";
      - acks {"t":"ack","id":<id>,"ok":bool[,"err":code]} go to the sender,
        only when the command carried an "id" -- except ping and list, which
        are always answered (CONTRACT 2.3).
      - every --period seconds (default 0.1) a telemetry frame
        {"t":"tags","seq":n,"ts":time.time(),"src":"<project slug>-backend",
         "tags":{tag: read_<ident>() for every tag}} goes to the static sink
        --sink HOST:PORT (default 127.0.0.1:5001) and every live subscriber.
        seq starts at 0 and wraps at 2**31. A read_ function that raises
        publishes null for that tag (never omits it).
  * CLI: --listen, --sink, --period, --frames N (exit after N frames; 0 =
    run forever, the default). SIGINT/SIGTERM exit cleanly (exit code 0).
  * No third-party imports; nothing at import time but definitions (the
    program runs under `if __name__ == "__main__": main()`).

The generated functions are the user's to edit, so write_scaffold never
overwrites an existing file unless overwrite=True; files already there are
reported in "skipped".
"""
from __future__ import annotations

import json
import os
import re

from designer.ide.design_index import DesignIndex

BACKEND_DIR = "backend"
FILES = ("backend.py", "tags.json", "tags.h", "README.md")
DEFAULT_LISTEN = "127.0.0.1:5010"
DEFAULT_SINK = "127.0.0.1:5001"


def tag_ident(tag: str) -> str:
    """A Python/C identifier for a tag: lowercase, every run of characters
    other than [a-z0-9] -> "_", stripped of leading/trailing "_"; a leading
    digit gets "t_" prepended. "ai.rpm" -> "ai_rpm", "mb.pump-1.sp" ->
    "mb_pump_1_sp"."""
    raise NotImplementedError  # W5


def project_slug(index: DesignIndex) -> str:
    """Lowercase project name with runs of non [a-z0-9] -> "-", stripped;
    "hmi" when that leaves nothing (no project / unnamed)."""
    raise NotImplementedError  # W5


def render_backend_py(index: DesignIndex) -> str:
    """The backend.py text. See the module docstring."""
    raise NotImplementedError  # W5


def render_tags_json(index: DesignIndex) -> str:
    """JSON text, indent 2, trailing newline:
    {"project": <project name>, "tags": [{"tag", "access", "writable",
     "declared", "readers": [widget ids], "writers": [widget ids]}, ...]}
    in index.tags() order; readers/writers without repeats, design order."""
    raise NotImplementedError  # W5


def render_tags_header(index: DesignIndex) -> str:
    """C header text:
        /* Generated by EmbeddedDisplay Studio from <project name>. */
        #ifndef <SLUG>_TAGS_H           (slug upper-cased, "-" -> "_")
        #define <SLUG>_TAGS_H
        #define TAG_<IDENT> "<tag>"     (one per tag, IDENT upper-cased)
        #define TAG_COUNT <n>
        #endif
    with a trailing newline."""
    raise NotImplementedError  # W5


def render_readme(index: DesignIndex) -> str:
    """Markdown: what the folder is, `python3 backend.py` usage with every
    CLI option, and how to point the panel's hmi-ui at it
    (HMI_UI_EXTRA_ARGS=--daemon-port 5010 in /etc/default/hmi-ui, as for
    tagsim), then a table of the tags (tag | access | used by)."""
    raise NotImplementedError  # W5


def write_scaffold(root: str, index: DesignIndex, overwrite: bool = False) -> dict:
    """Writes FILES into <root>/BACKEND_DIR (created when missing).

    Returns {"written": [abs paths], "skipped": [abs paths]} in FILES order.
    An existing file is skipped unless overwrite. Each write is atomic
    (temp file in the same folder + os.replace), UTF-8, "\\n" newlines.
    root must be an existing directory (else ValueError); index with no
    tags still writes a backend that publishes an empty "tags" object."""
    raise NotImplementedError  # W5


__all__ = ["tag_ident", "project_slug", "render_backend_py", "render_tags_json", "render_tags_header",
           "render_readme", "write_scaffold", "BACKEND_DIR", "FILES", "DEFAULT_LISTEN", "DEFAULT_SINK"]

_ = (json, os, re)
