"""designer/ide/backend_scaffold.py -- a working backend for the design's tags.

A Studio design invents tags ("ai.rpm", "do.pump") that no hardware
publishes yet. The Code section's "Generate backend..." writes a small,
runnable backend into the project folder that speaks the panel's wire
protocol (docs/CONTRACT.md section 2) for exactly those tags, with one stub
function per tag for the user -- or the coding agent -- to fill in:

    <project>/backend/
        backend.py   standalone, Python 3.8+ standard library only
        tags.json    the tag catalogue (see render_tags_json)
        tags.h       C constants for the tag names (see render_tags_header)
        README.md    how to run it and point the panel at it

backend.py (render_backend_py) -- the generated program:
  * `TAGS`: dict {tag: {"access": "R"|"W"|"RW"|"", "writable": bool}} in
    tag order (all index.tags()).
  * One function per tag, `read_<ident>()` for every tag, returning a
    placeholder: bool tags ("di."/"do." prefixes) False, "sys.uptime"
    seconds since start, everything else 0.0. `ident` = tag_ident(tag).
  * One function per writable tag, `write_<ident>(value)`, storing the value
    so the next read returns it (the placeholder "hardware"), returning True.
  * Wire protocol, CONTRACT 2:
      - listens for commands on --listen HOST:PORT (default 127.0.0.1:5010;
        5000 belongs to hmi-hwd), one JSON object per datagram, max 8192
        bytes (larger: dropped);
      - "set" {tag, value}: unknown tag -> ack err "unknown_tag"; tag not in
        the writable set -> "not_writable"; value not bool/int/float ->
        "bad_value"; else write_<ident>(value) -> ack ok;
      - "pulse" {tag, ms}: writable check as set, ms int 1..10000 else
        "bad_value"; writes True now and False after ms (a threading.Timer),
        ack ok;
      - "subscribe" {ttl?}: adds the sender to the subscribers for ttl
        seconds (default 5, capped at 60); "unsubscribe" removes it;
      - "list": ack ok with "tags": sorted tag names;
      - "ping": ack ok;
      - anything else: "unknown_cmd"; non-JSON "bad_json"; JSON that is not
        an object "not_an_object";
      - acks {"t":"ack","id":<id>,"ok":bool[,"err":code]} go to the sender,
        only when the command carried an "id" -- except ping and list, which
        are always answered (CONTRACT 2.3), and bad_json / not_an_object,
        which are always answered because such a datagram cannot carry one.
      - every --period seconds (default 0.1) a telemetry frame
        {"t":"tags","seq":n,"ts":time.time(),"src":"<project slug>-backend",
         "tags":{tag: read_<ident>() for every tag}} goes to the static sink
        --sink HOST:PORT (default 127.0.0.1:5001) and every live subscriber.
        seq starts at 0 and wraps at 2**31. A read_ function that raises
        publishes null for that tag (never omits it).
  * CLI: --listen, --sink, --period, --frames N (exit after N frames; 0 =
    run forever, the default). SIGINT/SIGTERM exit cleanly (exit code 0).
  * No third-party imports; nothing at import time but definitions (the
    program runs under `if __name__ == "__main__": main()`).

The generated functions are the user's to edit, so write_scaffold never
overwrites an existing file unless overwrite=True; files already there are
reported in "skipped".
"""
from __future__ import annotations

import json
import os
import re
import tempfile

from designer.ide.design_index import DesignIndex

BACKEND_DIR = "backend"
FILES = ("backend.py", "tags.json", "tags.h", "README.md")
DEFAULT_LISTEN = "127.0.0.1:5010"
DEFAULT_SINK = "127.0.0.1:5001"

# Markers the renderer fills in one pass (re.sub), so generated text is
# never scanned for markers again: a tag literally named "@@TAGS@@" stays data.
_MARKER = re.compile(r"@@([A-Z]+)@@")

_BACKEND_TEMPLATE = '''\
#!/usr/bin/env python3
"""Backend for a Studio design's tags, generated by EmbeddedDisplay Studio.

Speaks the panel's wire protocol (docs/CONTRACT.md section 2): JSON commands
arrive on --listen, and every --period seconds a telemetry frame with every
tag goes to --sink and to each live subscriber. The read_/write_ functions
below are placeholders for the real hardware: fill them in.

    python3 backend.py [--listen HOST:PORT] [--sink HOST:PORT]
                       [--period SECONDS] [--frames N]

Standard library only; Python 3.8+.
"""
import argparse
import json
import math
import signal
import socket
import sys
import threading
import time

PROJECT = @@PROJECT@@
SRC = @@SRC@@
DEFAULT_LISTEN = @@LISTEN@@
DEFAULT_SINK = @@SINK@@
DEFAULT_PERIOD = 0.1
MAX_DATAGRAM = 8192
SEQ_WRAP = 2 ** 31
SUBSCRIBE_TTL = 5.0
MAX_TTL = 60.0
PULSE_MS = (1, 10000)

# Every tag of the design, in tag order: access is what the design does with
# it ("R" read, "W" written, "RW", "" declared but unused).
TAGS = @@TAGS@@

_START = time.monotonic()
# The pulse release runs on a threading.Timer, so the store is shared.
_LOCK = threading.Lock()
_STORE = {}


# --- placeholder hardware: replace these with real reads and writes --------
@@FUNCTIONS@@


READERS = @@READERS@@

WRITERS = @@WRITERS@@


# --- wire protocol (CONTRACT 2) ---------------------------------------------

def _is_value(value):
    """bool/int/float and finite: NaN or inf would make a frame invalid JSON."""
    if isinstance(value, bool) or isinstance(value, int):
        return True
    return isinstance(value, float) and math.isfinite(value)


def _publishable(value):
    if value is None or isinstance(value, str) or _is_value(value):
        return value
    return None


def read_all():
    """{tag: value} for every tag; a read that fails publishes null."""
    values = {}
    for tag, read in READERS.items():
        try:
            value = _publishable(read())
        except Exception:
            value = None
        values[tag] = value
    return values


class Server:
    def __init__(self, sock):
        self.sock = sock
        self.seq = 0
        self.subscribers = {}  # (host, port) -> monotonic expiry
        self.timers = {}       # tag -> pending pulse release
        self.dropped = 0       # datagrams over MAX_DATAGRAM

    # -- commands

    def handle(self, data, addr):
        if len(data) > MAX_DATAGRAM:
            self.dropped += 1
            return
        try:
            msg = json.loads(data.decode("utf-8"))
        except (UnicodeDecodeError, ValueError, RecursionError):
            # No id can be read back, so the sender still hears why.
            self.reply(addr, {}, False, "bad_json")
            return
        if not isinstance(msg, dict):
            self.reply(addr, {}, False, "not_an_object")
            return
        cmd = msg.get("cmd")
        ok, err, extra = self.run(cmd, msg, addr)
        if "id" in msg or cmd in ("ping", "list"):
            self.reply(addr, msg, ok, err, extra)

    def run(self, cmd, msg, addr):
        if cmd == "ping":
            return True, None, None
        if cmd == "list":
            return True, None, {"tags": sorted(TAGS)}
        if cmd == "subscribe":
            return self.subscribe(msg, addr)
        if cmd == "unsubscribe":
            self.subscribers.pop(addr, None)
            return True, None, None
        if cmd in ("set", "pulse"):
            tag = msg.get("tag")
            if not isinstance(tag, str) or tag not in TAGS:
                return False, "unknown_tag", None
            if tag not in WRITERS:
                return False, "not_writable", None
            if cmd == "set":
                value = msg.get("value")
                if not _is_value(value):
                    return False, "bad_value", None
                return self.write(tag, value)
            return self.pulse(tag, msg.get("ms"))
        return False, "unknown_cmd", None

    def write(self, tag, value):
        try:
            ok = WRITERS[tag](value)
        except Exception:
            ok = False
        return (True, None, None) if ok is not False else (False, "hw_error", None)

    def pulse(self, tag, ms):
        if isinstance(ms, bool) or not isinstance(ms, int) or not PULSE_MS[0] <= ms <= PULSE_MS[1]:
            return False, "bad_value", None
        result = self.write(tag, True)
        if result[0]:
            # A new pulse restarts the hold instead of being cut short by
            # the previous pulse's release.
            old = self.timers.pop(tag, None)
            if old is not None:
                old.cancel()
            timer = threading.Timer(ms / 1000.0, self.release, (tag,))
            timer.daemon = True
            self.timers[tag] = timer
            timer.start()
        return result

    def release(self, tag):
        try:
            WRITERS[tag](False)
        except Exception:
            pass

    def subscribe(self, msg, addr):
        ttl = msg.get("ttl")
        if ttl is None:
            ttl = SUBSCRIBE_TTL
        elif not _is_value(ttl) or isinstance(ttl, bool):
            return False, "bad_value", None
        self.subscribers[addr] = time.monotonic() + min(max(float(ttl), 0.0), MAX_TTL)
        return True, None, None

    def reply(self, addr, msg, ok, err=None, extra=None):
        ack = {"t": "ack"}
        if "id" in msg:
            ack["id"] = msg["id"]
        ack["ok"] = ok
        if err:
            ack["err"] = err
        if extra:
            ack.update(extra)
        self.send(json.dumps(ack, separators=(",", ":")).encode("utf-8"), addr)

    def send(self, data, addr):
        try:
            self.sock.sendto(data, addr)
        except OSError:
            pass  # nobody listening there; UDP carries on

    # -- telemetry

    def live_subscribers(self):
        now = time.monotonic()
        for addr in [a for a, expiry in self.subscribers.items() if expiry <= now]:
            del self.subscribers[addr]
        return list(self.subscribers)

    def publish(self, sink):
        frame = {"t": "tags", "seq": self.seq, "ts": time.time(), "src": SRC, "tags": read_all()}
        self.seq = (self.seq + 1) % SEQ_WRAP
        data = json.dumps(frame, separators=(",", ":")).encode("utf-8")
        self.send(data, sink)
        for addr in self.live_subscribers():
            if addr != sink:
                self.send(data, addr)

    def serve(self, sink, period, frames, stop):
        sent = 0
        due = time.monotonic()
        while not stop.is_set():
            now = time.monotonic()
            if now >= due:
                self.publish(sink)
                sent += 1
                if frames and sent >= frames:
                    break
                due += period
                if due < now:
                    due = now + period  # after a stall, do not burst to catch up
                continue
            # Short waits so a signal's stop flag is seen promptly.
            self.sock.settimeout(max(0.001, min(due - now, 0.05)))
            try:
                data, addr = self.sock.recvfrom(65536)
            except OSError:
                # Timeout, or (Windows) a reset from an earlier send to a
                # closed port: neither concerns the next command.
                continue
            self.handle(data, addr)

    def close(self):
        for timer in self.timers.values():
            timer.cancel()
        self.sock.close()


# --- command line -------------------------------------------------------------

def _address(text):
    host, sep, port = text.rpartition(":")
    if not sep or not port.isdigit() or not 0 < int(port) < 65536:
        raise argparse.ArgumentTypeError("expected HOST:PORT, got %r" % text)
    return (host or "127.0.0.1", int(port))


def _period(text):
    value = float(text)
    if not math.isfinite(value) or value <= 0:
        raise argparse.ArgumentTypeError("period must be > 0 seconds")
    return value


def _frames(text):
    value = int(text)
    if value < 0:
        raise argparse.ArgumentTypeError("frames must be >= 0")
    return value


def main(argv=None):
    parser = argparse.ArgumentParser(description="Tag backend for " + PROJECT + " (CONTRACT 2 over UDP).")
    parser.add_argument("--listen", type=_address, default=DEFAULT_LISTEN,
                        help="HOST:PORT commands arrive on (default %(default)s)")
    parser.add_argument("--sink", type=_address, default=DEFAULT_SINK,
                        help="HOST:PORT telemetry frames always go to (default %(default)s)")
    parser.add_argument("--period", type=_period, default=DEFAULT_PERIOD,
                        help="seconds between frames (default %(default)s)")
    parser.add_argument("--frames", type=_frames, default=0,
                        help="exit after N frames; 0 = run forever (default)")
    args = parser.parse_args(argv)

    stop = threading.Event()

    def on_signal(signum, frame):
        stop.set()

    for name in ("SIGTERM", "SIGINT"):
        sig = getattr(signal, name, None)
        if sig is not None:
            try:
                signal.signal(sig, on_signal)
            except (OSError, ValueError):
                pass  # not the main thread, or not supported here

    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        sock.bind(args.listen)
    except OSError as exc:
        sock.close()
        sys.stderr.write("cannot listen on %s:%d: %s\\n" % (args.listen[0], args.listen[1], exc))
        return 1
    server = Server(sock)
    try:
        server.serve(args.sink, args.period, args.frames, stop)
    finally:
        server.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


def tag_ident(tag: str) -> str:
    """A Python/C identifier for a tag: lowercase, every run of characters
    other than [a-z0-9] -> "_", stripped of leading/trailing "_"; a leading
    digit gets "t_" prepended. "ai.rpm" -> "ai_rpm", "mb.pump-1.sp" ->
    "mb_pump_1_sp"."""
    ident = re.sub(r"[^a-z0-9]+", "_", tag.lower()).strip("_")
    if ident[:1].isdigit():
        ident = "t_" + ident
    return ident


def project_slug(index: DesignIndex) -> str:
    """Lowercase project name with runs of non [a-z0-9] -> "-", stripped;
    "hmi" when that leaves nothing (no project / unnamed)."""
    slug = re.sub(r"[^a-z0-9]+", "-", _project_name(index).lower()).strip("-")
    return slug or "hmi"


def _project_name(index: DesignIndex) -> str:
    return str(getattr(index.project, "name", "") or "")


def _idents(index: DesignIndex) -> dict:
    """{tag: identifier}, unique: "ai.a_b" and "ai.a.b" both map to "ai_a_b",
    and two functions of one name would silently shadow each other, so later
    tags get "_2", "_3", ..."""
    idents: dict = {}
    taken: set = set()
    for entry in index.tags():
        base = tag_ident(entry.tag) or "tag"
        ident, n = base, 1
        while ident in taken:
            n += 1
            ident = f"{base}_{n}"
        taken.add(ident)
        idents[entry.tag] = ident
    return idents


def _placeholder(tag: str) -> str:
    """Python source of a tag's placeholder value."""
    if tag.startswith(("di.", "do.")):
        return "False"
    return "0.0"


def _functions(index: DesignIndex, idents: dict) -> str:
    out = []
    for entry in index.tags():
        tag, ident = entry.tag, idents[entry.tag]
        users = ", ".join(index.widgets_using(tag))
        # repr() keeps the comment on one line whatever the tag holds.
        out.append(f"\n\n\n# {tag!r} ({entry.access or '-'}), used by "
                   + (repr(users) if users else "no widget") + "\n")
        if entry.writable:
            out.append(f"def read_{ident}():\n"
                       f"    with _LOCK:\n"
                       f"        return _STORE.get({tag!r}, {_placeholder(tag)})\n"
                       f"\n\n"
                       f"def write_{ident}(value):\n"
                       f"    with _LOCK:\n"
                       f"        _STORE[{tag!r}] = value\n"
                       f"    return True")
        elif tag == "sys.uptime":
            out.append(f"def read_{ident}():\n"
                       f"    return time.monotonic() - _START")
        else:
            out.append(f"def read_{ident}():\n"
                       f"    return {_placeholder(tag)}")
    return "".join(out)


def _dict_source(pairs: list) -> str:
    """A dict literal, one pair per line; keys and values already source."""
    if not pairs:
        return "{}"
    return "{\n" + "".join(f"    {key}: {value},\n" for key, value in pairs) + "}"


def render_backend_py(index: DesignIndex) -> str:
    """The backend.py text. See the module docstring."""
    tags = index.tags()
    idents = _idents(index)
    fills = {
        "PROJECT": repr(_project_name(index)),
        "SRC": repr(project_slug(index) + "-backend"),
        "LISTEN": repr(DEFAULT_LISTEN),
        "SINK": repr(DEFAULT_SINK),
        "TAGS": _dict_source([(repr(e.tag), repr({"access": e.access, "writable": bool(e.writable)}))
                              for e in tags]),
        "FUNCTIONS": _functions(index, idents),
        "READERS": _dict_source([(repr(e.tag), f"read_{idents[e.tag]}") for e in tags]),
        "WRITERS": _dict_source([(repr(e.tag), f"write_{idents[e.tag]}") for e in tags if e.writable]),
    }
    return _MARKER.sub(lambda m: fills[m.group(1)], _BACKEND_TEMPLATE)


def _unique(ids) -> list:
    out: list = []
    for wid in ids:
        if wid and wid not in out:
            out.append(wid)
    return out


def render_tags_json(index: DesignIndex) -> str:
    """JSON text, indent 2, trailing newline:
    {"project": <project name>, "tags": [{"tag", "access", "writable",
     "declared", "readers": [widget ids], "writers": [widget ids]}, ...]}
    in index.tags() order; readers/writers without repeats, design order."""
    tags = [{"tag": e.tag, "access": e.access, "writable": bool(e.writable), "declared": bool(e.declared),
             "readers": _unique(wid for wid, _ in e.readers),
             "writers": _unique(wid for wid, _ in e.writers)}
            for e in index.tags()]
    return json.dumps({"project": _project_name(index), "tags": tags}, indent=2) + "\n"


def render_tags_header(index: DesignIndex) -> str:
    """C header text:
        /* Generated by EmbeddedDisplay Studio from <project name>. */
        #ifndef <SLUG>_TAGS_H           (slug upper-cased, "-" -> "_")
        #define <SLUG>_TAGS_H
        #define TAG_<IDENT> "<tag>"     (one per tag, IDENT upper-cased)
        #define TAG_COUNT <n>
        #endif
    with a trailing newline."""
    # A "*/" or a line break in the name would end the comment early.
    name = " ".join(_project_name(index).replace("*/", "* /").split())
    guard = project_slug(index).upper().replace("-", "_") + "_TAGS_H"
    if guard[:1].isdigit():
        guard = "_" + guard
    idents = _idents(index)
    lines = [f"/* Generated by EmbeddedDisplay Studio from {name}. */",
             f"#ifndef {guard}",
             f"#define {guard}"]
    # json.dumps escapes quotes, backslashes and control characters the
    # way a C string literal wants them.
    lines += [f"#define TAG_{idents[e.tag].upper()} {json.dumps(e.tag)}" for e in index.tags()]
    lines += [f"#define TAG_COUNT {len(index.tags())}", "#endif"]
    return "\n".join(lines) + "\n"


def _cell(text: str) -> str:
    return " ".join(str(text).replace("|", "\\|").split()) or "-"


def render_readme(index: DesignIndex) -> str:
    """Markdown: what the folder is, `python3 backend.py` usage with every
    CLI option, and how to point the panel's hmi-ui at it
    (HMI_UI_EXTRA_ARGS=--daemon-port 5010 in /etc/default/hmi-ui, as for
    tagsim), then a table of the tags (tag | access | used by)."""
    name = _project_name(index) or "an unnamed design"
    lines = [
        f"# Backend for {_cell(name)}",
        "",
        "Generated by EmbeddedDisplay Studio. `backend.py` is a small, runnable",
        "backend that speaks the panel's wire protocol (docs/CONTRACT.md section 2)",
        "for exactly the tags this design uses: JSON commands over UDP in, a",
        "telemetry frame of every tag out. Each tag has a `read_<tag>()` stub and",
        "each writable tag a `write_<tag>(value)` stub returning placeholder values;",
        "fill them in with the real hardware. `tags.json` is the tag catalogue and",
        "`tags.h` the tag names as C constants. Standard library only, Python 3.8+.",
        "",
        "## Run",
        "",
        "```",
        "python3 backend.py [--listen HOST:PORT] [--sink HOST:PORT] [--period SECONDS] [--frames N]",
        "```",
        "",
        f"- `--listen HOST:PORT` -- where commands arrive (default `{DEFAULT_LISTEN}`; 5000 belongs to hmi-hwd).",
        f"- `--sink HOST:PORT` -- where every telemetry frame goes (default `{DEFAULT_SINK}`).",
        "- `--period SECONDS` -- time between frames (default `0.1`).",
        "- `--frames N` -- exit after N frames; `0` runs forever (default).",
        "",
        "Ctrl+C or SIGTERM stops it cleanly.",
        "",
        "## Point the panel at it",
        "",
        "As for tagsim, tell hmi-ui to send its commands here: in `/etc/default/hmi-ui` set",
        "",
        "```",
        "HMI_UI_EXTRA_ARGS=--daemon-port 5010",
        "```",
        "",
        "then restart hmi-ui (`systemctl restart hmi-ui`).",
        "",
        "## Tags",
        "",
        "| tag | access | used by |",
        "| --- | --- | --- |",
    ]
    for entry in index.tags():
        users = ", ".join(index.widgets_using(entry.tag))
        lines.append(f"| `{_cell(entry.tag)}` | {_cell(entry.access)} | {_cell(users)} |")
    if not index.tags():
        lines.append("| - | - | - |")
    return "\n".join(lines) + "\n"


def write_scaffold(root: str, index: DesignIndex, overwrite: bool = False) -> dict:
    """Writes FILES into <root>/BACKEND_DIR (created when missing).

    Returns {"written": [abs paths], "skipped": [abs paths]} in FILES order.
    An existing file is skipped unless overwrite. Each write is atomic
    (temp file in the same folder + os.replace), UTF-8, "\\n" newlines.
    root must be an existing directory (else ValueError); index with no
    tags still writes a backend that publishes an empty "tags" object."""
    if not root or not os.path.isdir(root):
        raise ValueError(f"not an existing directory: {root!r}")
    folder = os.path.abspath(os.path.join(root, BACKEND_DIR))
    # Render everything before touching the disk: a render error then
    # leaves nothing half-written.
    texts = {"backend.py": render_backend_py(index), "tags.json": render_tags_json(index),
             "tags.h": render_tags_header(index), "README.md": render_readme(index)}
    os.makedirs(folder, exist_ok=True)
    result: dict = {"written": [], "skipped": []}
    for name in FILES:
        path = os.path.join(folder, name)
        if os.path.exists(path) and not overwrite:
            result["skipped"].append(path)
            continue
        fd, temp = tempfile.mkstemp(prefix="." + name + ".", suffix=".tmp", dir=folder)
        try:
            with open(fd, "w", encoding="utf-8", newline="\n") as f:
                f.write(texts[name])
            # mkstemp makes the file 0600; these are ordinary project files
            # (and backend.py is run directly).
            os.chmod(temp, 0o755 if name == "backend.py" else 0o644)
            os.replace(temp, path)
        except BaseException:
            try:
                os.remove(temp)
            except OSError:
                pass
            raise
        result["written"].append(path)
    return result


__all__ = ["tag_ident", "project_slug", "render_backend_py", "render_tags_json", "render_tags_header",
           "render_readme", "write_scaffold", "BACKEND_DIR", "FILES", "DEFAULT_LISTEN", "DEFAULT_SINK"]

_ = (json, os, re)
