"""Generate the C runtime's frozen contract from the Designer's own tables.

    python native/hmi-ui/schema/gen_schema.py          # writes the files below
    python native/hmi-ui/schema/gen_schema.py --check  # exit 1 if they are stale

Outputs (all generated, never hand-edited):
    native/hmi-ui/schema/kit_schema.json    widget types, properties, defaults,
                                            bindable props, signals, containers,
                                            binding rule tables, theme colours
    native/hmi-ui/src/gen/kit_schema.h/.c   the same as C tables

Sources of truth: designer/palette/widget_registry.py (what the Designer can
place and with which properties), designer/generators/qml_generator.py (how
bindings, thresholds and actions become behaviour) and ui/qml/Shadcn/Theme.qml
(the colour tokens). tests/test_hmi_ui_schema.py fails when these move and
the generated files were not refreshed, so the C kit cannot drift from the
Studio.
"""
import json
import os
import re
import sys

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
sys.path.insert(0, REPO)
OUT_JSON = os.path.join(REPO, "native", "hmi-ui", "schema", "kit_schema.json")
OUT_H = os.path.join(REPO, "native", "hmi-ui", "src", "gen", "kit_schema.h")
OUT_C = os.path.join(REPO, "native", "hmi-ui", "src", "gen", "kit_schema.c")

from designer.palette.widget_registry import default_registry  # noqa: E402
from designer.generators import qml_generator as gen  # noqa: E402

KIND = {bool: "bool", int: "int", float: "float", str: "str", list: "list"}


def theme_colours():
    """{name: {"light": "#..", "dark": "#.."}} from Theme.qml."""
    text = open(os.path.join(REPO, "ui", "qml", "Shadcn", "Theme.qml"), encoding="utf-8").read()
    out = {}
    two = re.compile(r'readonly property color (\w+): mode === "light" \? "(#[0-9a-fA-F]+)" : "(#[0-9a-fA-F]+)"')
    one = re.compile(r'readonly property color (\w+): "(#[0-9a-fA-F]+)"')
    for m in two.finditer(text):
        out[m.group(1)] = {"light": m.group(2), "dark": m.group(3)}
    for m in one.finditer(text):
        out.setdefault(m.group(1), {"light": m.group(2), "dark": m.group(2)})
    return out


def build():
    registry = default_registry()
    types = {}
    for d in sorted(registry.definitions(), key=lambda d: d.type):
        props = {}
        for name, typ in d.properties.items():
            kind = KIND.get(typ, "str")
            if name in (d.color_properties or ()):
                kind = "color"
            props[name] = {"kind": kind, "default": d.defaults.get(name)}
        types[d.type] = {
            "qml": d.qml_component,
            "category": d.category,
            "display_name": d.display_name,
            "default_width": d.default_width,
            "default_height": d.default_height,
            "container": bool(d.container),
            "state_property": getattr(d, "state_property", "") or "",
            "properties": props,
            "bindable": list(d.bindable_properties),
            "signals": list(d.action_signals),
            "choices": {k: list(v) for k, v in (d.choices or {}).items()},
            "assets": list(d.asset_properties or ()),
        }
    return {
        "_generated_by": "native/hmi-ui/schema/gen_schema.py -- do not edit",
        "types": types,
        "positioners": list(gen.POSITIONERS),
        "series_properties": sorted([list(x) for x in gen.SERIES_PROPERTIES]),
        "state_properties": {k: {"property": v[0], "levels": list(v[1])} for k, v in gen.STATE_PROPERTIES.items()},
        "threshold_properties": gen.THRESHOLD_PROPERTIES,
        "sim_tags": sorted(gen._SIM_TAGS),
        "theme": theme_colours(),
    }


def c_str(s):
    if s is None:
        return "NULL"
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def default_str(v):
    if v is None:
        return None
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (list, tuple)):
        return ",".join(str(x) for x in v)
    return str(v)


def render_c(schema):
    h = ['// GENERATED by native/hmi-ui/schema/gen_schema.py -- do not edit.',
         '// The widget kit contract: every type the Designer can place, its',
         '// properties with defaults, and the theme colours, straight from the',
         '// Studio\'s registry and Theme.qml.',
         '#pragma once', '#include <stdbool.h>', '#include <stddef.h>', '',
         'typedef enum { HMI_KIND_BOOL, HMI_KIND_INT, HMI_KIND_FLOAT, HMI_KIND_STR, HMI_KIND_COLOR, HMI_KIND_LIST } hmi_prop_kind_t;',
         '',
         'typedef struct { const char *name; hmi_prop_kind_t kind; const char *default_value; /* NULL = none */ bool bindable; } hmi_prop_schema_t;',
         '',
         'typedef struct {',
         '    const char *type; const char *category; int default_width; int default_height; bool container;',
         '    const char *state_property; /* "" when none */',
         '    const hmi_prop_schema_t *props; size_t nprops;',
         '    const char *const *signals; size_t nsignals;',
         '} hmi_type_schema_t;',
         '',
         'typedef struct { const char *name; const char *light; const char *dark; } hmi_theme_colour_t;',
         '',
         'extern const hmi_type_schema_t hmi_kit_types[];', 'extern const size_t hmi_kit_type_count;',
         'extern const hmi_theme_colour_t hmi_theme_colours[];', 'extern const size_t hmi_theme_colour_count;',
         '', 'const hmi_type_schema_t *hmi_kit_find(const char *type);',
         'const hmi_prop_schema_t *hmi_kit_find_prop(const hmi_type_schema_t *t, const char *prop);',
         'const char *hmi_theme_colour(const char *name, bool dark); /* NULL when unknown */', '']
    c = ['// GENERATED by native/hmi-ui/schema/gen_schema.py -- do not edit.',
         '#include "kit_schema.h"', '#include <string.h>', '']
    kinds = {"bool": "HMI_KIND_BOOL", "int": "HMI_KIND_INT", "float": "HMI_KIND_FLOAT",
             "str": "HMI_KIND_STR", "color": "HMI_KIND_COLOR", "list": "HMI_KIND_LIST"}
    for name, t in schema["types"].items():
        ident = re.sub(r"\W", "_", name)
        c.append(f"static const hmi_prop_schema_t props_{ident}[] = {{")
        for pname, p in t["properties"].items():
            c.append(f'    {{{c_str(pname)}, {kinds[p["kind"]]}, {c_str(default_str(p["default"]))}, {"true" if pname in t["bindable"] else "false"}}},')
        c.append("    {NULL, HMI_KIND_STR, NULL, false}")
        c.append("};")
        c.append(f"static const char *const signals_{ident}[] = {{" + ", ".join(c_str(s) for s in t["signals"]) + ("," if t["signals"] else "") + " NULL};")
    c.append("")
    c.append("const hmi_type_schema_t hmi_kit_types[] = {")
    for name, t in schema["types"].items():
        ident = re.sub(r"\W", "_", name)
        c.append(f'    {{{c_str(name)}, {c_str(t["category"])}, {t["default_width"]}, {t["default_height"]}, '
                 f'{"true" if t["container"] else "false"}, {c_str(t["state_property"])}, '
                 f'props_{ident}, {len(t["properties"])}, signals_{ident}, {len(t["signals"])}}},')
    c.append("};")
    c.append(f"const size_t hmi_kit_type_count = {len(schema['types'])};")
    c.append("")
    c.append("const hmi_theme_colour_t hmi_theme_colours[] = {")
    for name, v in schema["theme"].items():
        c.append(f'    {{{c_str(name)}, {c_str(v["light"])}, {c_str(v["dark"])}}},')
    c.append("};")
    c.append(f"const size_t hmi_theme_colour_count = {len(schema['theme'])};")
    c += ['',
          'const hmi_type_schema_t *hmi_kit_find(const char *type)',
          '{',
          '    for (size_t i = 0; i < hmi_kit_type_count; ++i)',
          '        if (strcmp(hmi_kit_types[i].type, type) == 0) return &hmi_kit_types[i];',
          '    return NULL;',
          '}',
          '',
          'const hmi_prop_schema_t *hmi_kit_find_prop(const hmi_type_schema_t *t, const char *prop)',
          '{',
          '    if (!t) return NULL;',
          '    for (size_t i = 0; i < t->nprops; ++i)',
          '        if (strcmp(t->props[i].name, prop) == 0) return &t->props[i];',
          '    return NULL;',
          '}',
          '',
          'const char *hmi_theme_colour(const char *name, bool dark)',
          '{',
          '    for (size_t i = 0; i < hmi_theme_colour_count; ++i)',
          '        if (strcmp(hmi_theme_colours[i].name, name) == 0)',
          '            return dark ? hmi_theme_colours[i].dark : hmi_theme_colours[i].light;',
          '    return NULL;',
          '}', '']
    return "\n".join(h), "\n".join(c)


def main():
    schema = build()
    js = json.dumps(schema, indent=1, sort_keys=False) + "\n"
    h, c = render_c(schema)
    outputs = {OUT_JSON: js, OUT_H: h, OUT_C: c}
    if "--check" in sys.argv:
        stale = [p for p, s in outputs.items()
                 if not os.path.exists(p) or open(p, encoding="utf-8", newline="").read() != s]
        for p in stale:
            print("stale:", os.path.relpath(p, REPO))
        return 1 if stale else 0
    for p, s in outputs.items():
        os.makedirs(os.path.dirname(p), exist_ok=True)
        with open(p, "w", encoding="utf-8", newline="\n") as f:
            f.write(s)
        print("wrote", os.path.relpath(p, REPO))
    return 0


if __name__ == "__main__":
    sys.exit(main())
